/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: c_peer2peer_netmessages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "c_peer2peer_netmessages.pb-c.h"
void   cp2_p__text_message__init
                     (CP2PTextMessage         *message)
{
  static CP2PTextMessage init_value = CP2_P__TEXT_MESSAGE__INIT;
  *message = init_value;
}
size_t cp2_p__text_message__get_packed_size
                     (const CP2PTextMessage *message)
{
  assert(message->base.descriptor == &cp2_p__text_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cp2_p__text_message__pack
                     (const CP2PTextMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cp2_p__text_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cp2_p__text_message__pack_to_buffer
                     (const CP2PTextMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cp2_p__text_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CP2PTextMessage *
       cp2_p__text_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CP2PTextMessage *)
     protobuf_c_message_unpack (&cp2_p__text_message__descriptor,
                                allocator, len, data);
}
void   cp2_p__text_message__free_unpacked
                     (CP2PTextMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cp2_p__text_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   csteam__voice__encoding__init
                     (CSteamVoiceEncoding         *message)
{
  static CSteamVoiceEncoding init_value = CSTEAM__VOICE__ENCODING__INIT;
  *message = init_value;
}
size_t csteam__voice__encoding__get_packed_size
                     (const CSteamVoiceEncoding *message)
{
  assert(message->base.descriptor == &csteam__voice__encoding__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t csteam__voice__encoding__pack
                     (const CSteamVoiceEncoding *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &csteam__voice__encoding__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t csteam__voice__encoding__pack_to_buffer
                     (const CSteamVoiceEncoding *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &csteam__voice__encoding__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CSteamVoiceEncoding *
       csteam__voice__encoding__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CSteamVoiceEncoding *)
     protobuf_c_message_unpack (&csteam__voice__encoding__descriptor,
                                allocator, len, data);
}
void   csteam__voice__encoding__free_unpacked
                     (CSteamVoiceEncoding *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &csteam__voice__encoding__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cp2_p__voice__init
                     (CP2PVoice         *message)
{
  static CP2PVoice init_value = CP2_P__VOICE__INIT;
  *message = init_value;
}
size_t cp2_p__voice__get_packed_size
                     (const CP2PVoice *message)
{
  assert(message->base.descriptor == &cp2_p__voice__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cp2_p__voice__pack
                     (const CP2PVoice *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cp2_p__voice__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cp2_p__voice__pack_to_buffer
                     (const CP2PVoice *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cp2_p__voice__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CP2PVoice *
       cp2_p__voice__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CP2PVoice *)
     protobuf_c_message_unpack (&cp2_p__voice__descriptor,
                                allocator, len, data);
}
void   cp2_p__voice__free_unpacked
                     (CP2PVoice *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cp2_p__voice__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cp2_p__ping__init
                     (CP2PPing         *message)
{
  static CP2PPing init_value = CP2_P__PING__INIT;
  *message = init_value;
}
size_t cp2_p__ping__get_packed_size
                     (const CP2PPing *message)
{
  assert(message->base.descriptor == &cp2_p__ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cp2_p__ping__pack
                     (const CP2PPing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cp2_p__ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cp2_p__ping__pack_to_buffer
                     (const CP2PPing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cp2_p__ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CP2PPing *
       cp2_p__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CP2PPing *)
     protobuf_c_message_unpack (&cp2_p__ping__descriptor,
                                allocator, len, data);
}
void   cp2_p__ping__free_unpacked
                     (CP2PPing *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cp2_p__ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cp2_p__vravatar_position__corientation__init
                     (CP2PVRAvatarPosition__COrientation         *message)
{
  static CP2PVRAvatarPosition__COrientation init_value = CP2_P__VRAVATAR_POSITION__CORIENTATION__INIT;
  *message = init_value;
}
void   cp2_p__vravatar_position__init
                     (CP2PVRAvatarPosition         *message)
{
  static CP2PVRAvatarPosition init_value = CP2_P__VRAVATAR_POSITION__INIT;
  *message = init_value;
}
size_t cp2_p__vravatar_position__get_packed_size
                     (const CP2PVRAvatarPosition *message)
{
  assert(message->base.descriptor == &cp2_p__vravatar_position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cp2_p__vravatar_position__pack
                     (const CP2PVRAvatarPosition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cp2_p__vravatar_position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cp2_p__vravatar_position__pack_to_buffer
                     (const CP2PVRAvatarPosition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cp2_p__vravatar_position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CP2PVRAvatarPosition *
       cp2_p__vravatar_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CP2PVRAvatarPosition *)
     protobuf_c_message_unpack (&cp2_p__vravatar_position__descriptor,
                                allocator, len, data);
}
void   cp2_p__vravatar_position__free_unpacked
                     (CP2PVRAvatarPosition *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cp2_p__vravatar_position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cp2_p__watch_synchronization__init
                     (CP2PWatchSynchronization         *message)
{
  static CP2PWatchSynchronization init_value = CP2_P__WATCH_SYNCHRONIZATION__INIT;
  *message = init_value;
}
size_t cp2_p__watch_synchronization__get_packed_size
                     (const CP2PWatchSynchronization *message)
{
  assert(message->base.descriptor == &cp2_p__watch_synchronization__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cp2_p__watch_synchronization__pack
                     (const CP2PWatchSynchronization *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cp2_p__watch_synchronization__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cp2_p__watch_synchronization__pack_to_buffer
                     (const CP2PWatchSynchronization *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cp2_p__watch_synchronization__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CP2PWatchSynchronization *
       cp2_p__watch_synchronization__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CP2PWatchSynchronization *)
     protobuf_c_message_unpack (&cp2_p__watch_synchronization__descriptor,
                                allocator, len, data);
}
void   cp2_p__watch_synchronization__free_unpacked
                     (CP2PWatchSynchronization *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cp2_p__watch_synchronization__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cp2_p__text_message__field_descriptors[1] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CP2PTextMessage, has_text),
    offsetof(CP2PTextMessage, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cp2_p__text_message__field_indices_by_name[] = {
  0,   /* field[0] = text */
};
static const ProtobufCIntRange cp2_p__text_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cp2_p__text_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CP2P_TextMessage",
  "CP2PTextMessage",
  "CP2PTextMessage",
  "",
  sizeof(CP2PTextMessage),
  1,
  cp2_p__text_message__field_descriptors,
  cp2_p__text_message__field_indices_by_name,
  1,  cp2_p__text_message__number_ranges,
  (ProtobufCMessageInit) cp2_p__text_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor csteam__voice__encoding__field_descriptors[1] =
{
  {
    "voice_data",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CSteamVoiceEncoding, has_voice_data),
    offsetof(CSteamVoiceEncoding, voice_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned csteam__voice__encoding__field_indices_by_name[] = {
  0,   /* field[0] = voice_data */
};
static const ProtobufCIntRange csteam__voice__encoding__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor csteam__voice__encoding__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CSteam_Voice_Encoding",
  "CSteamVoiceEncoding",
  "CSteamVoiceEncoding",
  "",
  sizeof(CSteamVoiceEncoding),
  1,
  csteam__voice__encoding__field_descriptors,
  csteam__voice__encoding__field_indices_by_name,
  1,  csteam__voice__encoding__number_ranges,
  (ProtobufCMessageInit) csteam__voice__encoding__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue cp2_p__voice__handler__flags__enum_values_by_number[1] =
{
  { "Played_Audio", "CP2_P__VOICE__HANDLER__FLAGS__Played_Audio", 1 },
};
static const ProtobufCIntRange cp2_p__voice__handler__flags__value_ranges[] = {
{1, 0},{0, 1}
};
static const ProtobufCEnumValueIndex cp2_p__voice__handler__flags__enum_values_by_name[1] =
{
  { "Played_Audio", 0 },
};
const ProtobufCEnumDescriptor cp2_p__voice__handler__flags__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CP2P_Voice.Handler_Flags",
  "Handler_Flags",
  "CP2PVoice__HandlerFlags",
  "",
  1,
  cp2_p__voice__handler__flags__enum_values_by_number,
  1,
  cp2_p__voice__handler__flags__enum_values_by_name,
  1,
  cp2_p__voice__handler__flags__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor cp2_p__voice__field_descriptors[2] =
{
  {
    "audio",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CP2PVoice, audio),
    &cmsg_voice_audio__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "broadcast_group",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CP2PVoice, has_broadcast_group),
    offsetof(CP2PVoice, broadcast_group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cp2_p__voice__field_indices_by_name[] = {
  0,   /* field[0] = audio */
  1,   /* field[1] = broadcast_group */
};
static const ProtobufCIntRange cp2_p__voice__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cp2_p__voice__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CP2P_Voice",
  "CP2PVoice",
  "CP2PVoice",
  "",
  sizeof(CP2PVoice),
  2,
  cp2_p__voice__field_descriptors,
  cp2_p__voice__field_indices_by_name,
  1,  cp2_p__voice__number_ranges,
  (ProtobufCMessageInit) cp2_p__voice__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cp2_p__ping__field_descriptors[2] =
{
  {
    "send_time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(CP2PPing, send_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_reply",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(CP2PPing, is_reply),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cp2_p__ping__field_indices_by_name[] = {
  1,   /* field[1] = is_reply */
  0,   /* field[0] = send_time */
};
static const ProtobufCIntRange cp2_p__ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cp2_p__ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CP2P_Ping",
  "CP2PPing",
  "CP2PPing",
  "",
  sizeof(CP2PPing),
  2,
  cp2_p__ping__field_descriptors,
  cp2_p__ping__field_indices_by_name,
  1,  cp2_p__ping__number_ranges,
  (ProtobufCMessageInit) cp2_p__ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cp2_p__vravatar_position__corientation__field_descriptors[2] =
{
  {
    "pos",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CP2PVRAvatarPosition__COrientation, pos),
    &cmsg_vector__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ang",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CP2PVRAvatarPosition__COrientation, ang),
    &cmsg_qangle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cp2_p__vravatar_position__corientation__field_indices_by_name[] = {
  1,   /* field[1] = ang */
  0,   /* field[0] = pos */
};
static const ProtobufCIntRange cp2_p__vravatar_position__corientation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cp2_p__vravatar_position__corientation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CP2P_VRAvatarPosition.COrientation",
  "COrientation",
  "CP2PVRAvatarPosition__COrientation",
  "",
  sizeof(CP2PVRAvatarPosition__COrientation),
  2,
  cp2_p__vravatar_position__corientation__field_descriptors,
  cp2_p__vravatar_position__corientation__field_indices_by_name,
  1,  cp2_p__vravatar_position__corientation__number_ranges,
  (ProtobufCMessageInit) cp2_p__vravatar_position__corientation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cp2_p__vravatar_position__field_descriptors[2] =
{
  {
    "body_parts",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CP2PVRAvatarPosition, n_body_parts),
    offsetof(CP2PVRAvatarPosition, body_parts),
    &cp2_p__vravatar_position__corientation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hat_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CP2PVRAvatarPosition, has_hat_id),
    offsetof(CP2PVRAvatarPosition, hat_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cp2_p__vravatar_position__field_indices_by_name[] = {
  0,   /* field[0] = body_parts */
  1,   /* field[1] = hat_id */
};
static const ProtobufCIntRange cp2_p__vravatar_position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cp2_p__vravatar_position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CP2P_VRAvatarPosition",
  "CP2PVRAvatarPosition",
  "CP2PVRAvatarPosition",
  "",
  sizeof(CP2PVRAvatarPosition),
  2,
  cp2_p__vravatar_position__field_descriptors,
  cp2_p__vravatar_position__field_indices_by_name,
  1,  cp2_p__vravatar_position__number_ranges,
  (ProtobufCMessageInit) cp2_p__vravatar_position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cp2_p__watch_synchronization__field_descriptors[8] =
{
  {
    "demo_tick",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CP2PWatchSynchronization, has_demo_tick),
    offsetof(CP2PWatchSynchronization, demo_tick),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "paused",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CP2PWatchSynchronization, has_paused),
    offsetof(CP2PWatchSynchronization, paused),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tv_listen_voice_indices",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CP2PWatchSynchronization, has_tv_listen_voice_indices),
    offsetof(CP2PWatchSynchronization, tv_listen_voice_indices),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dota_spectator_mode",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CP2PWatchSynchronization, has_dota_spectator_mode),
    offsetof(CP2PWatchSynchronization, dota_spectator_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dota_spectator_watching_broadcaster",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CP2PWatchSynchronization, has_dota_spectator_watching_broadcaster),
    offsetof(CP2PWatchSynchronization, dota_spectator_watching_broadcaster),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dota_spectator_hero_index",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CP2PWatchSynchronization, has_dota_spectator_hero_index),
    offsetof(CP2PWatchSynchronization, dota_spectator_hero_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dota_spectator_autospeed",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CP2PWatchSynchronization, has_dota_spectator_autospeed),
    offsetof(CP2PWatchSynchronization, dota_spectator_autospeed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dota_replay_speed",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CP2PWatchSynchronization, has_dota_replay_speed),
    offsetof(CP2PWatchSynchronization, dota_replay_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cp2_p__watch_synchronization__field_indices_by_name[] = {
  0,   /* field[0] = demo_tick */
  7,   /* field[7] = dota_replay_speed */
  6,   /* field[6] = dota_spectator_autospeed */
  5,   /* field[5] = dota_spectator_hero_index */
  3,   /* field[3] = dota_spectator_mode */
  4,   /* field[4] = dota_spectator_watching_broadcaster */
  1,   /* field[1] = paused */
  2,   /* field[2] = tv_listen_voice_indices */
};
static const ProtobufCIntRange cp2_p__watch_synchronization__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor cp2_p__watch_synchronization__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CP2P_WatchSynchronization",
  "CP2PWatchSynchronization",
  "CP2PWatchSynchronization",
  "",
  sizeof(CP2PWatchSynchronization),
  8,
  cp2_p__watch_synchronization__field_descriptors,
  cp2_p__watch_synchronization__field_indices_by_name,
  1,  cp2_p__watch_synchronization__number_ranges,
  (ProtobufCMessageInit) cp2_p__watch_synchronization__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue p2_p__messages__enum_values_by_number[5] =
{
  { "p2p_TextMessage", "P2_P__MESSAGES__p2p_TextMessage", 256 },
  { "p2p_Voice", "P2_P__MESSAGES__p2p_Voice", 257 },
  { "p2p_Ping", "P2_P__MESSAGES__p2p_Ping", 258 },
  { "p2p_VRAvatarPosition", "P2_P__MESSAGES__p2p_VRAvatarPosition", 259 },
  { "p2p_WatchSynchronization", "P2_P__MESSAGES__p2p_WatchSynchronization", 260 },
};
static const ProtobufCIntRange p2_p__messages__value_ranges[] = {
{256, 0},{0, 5}
};
static const ProtobufCEnumValueIndex p2_p__messages__enum_values_by_name[5] =
{
  { "p2p_Ping", 2 },
  { "p2p_TextMessage", 0 },
  { "p2p_VRAvatarPosition", 3 },
  { "p2p_Voice", 1 },
  { "p2p_WatchSynchronization", 4 },
};
const ProtobufCEnumDescriptor p2_p__messages__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "P2P_Messages",
  "P2P_Messages",
  "P2PMessages",
  "",
  5,
  p2_p__messages__enum_values_by_number,
  5,
  p2_p__messages__enum_values_by_name,
  1,
  p2_p__messages__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
