/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: clientmessages.proto */

#ifndef PROTOBUF_C_clientmessages_2eproto__INCLUDED
#define PROTOBUF_C_clientmessages_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _CClientMsgCustomGameEvent CClientMsgCustomGameEvent;
typedef struct _CClientMsgClientUIEvent CClientMsgClientUIEvent;


/* --- enums --- */

typedef enum _EBaseClientMessages {
  EBASE_CLIENT_MESSAGES__CM_CustomGameEvent = 280,
  EBASE_CLIENT_MESSAGES__CM_ClientUIEvent = 282,
  EBASE_CLIENT_MESSAGES__CM_MAX_BASE = 300
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EBASE_CLIENT_MESSAGES)
} EBaseClientMessages;
typedef enum _EClientUIEvent {
  ECLIENT_UIEVENT__EClientUIEvent_Invalid = 0,
  ECLIENT_UIEVENT__EClientUIEvent_DialogFinished = 1,
  ECLIENT_UIEVENT__EClientUIEvent_FireOutput = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ECLIENT_UIEVENT)
} EClientUIEvent;

/* --- messages --- */

struct  _CClientMsgCustomGameEvent
{
  ProtobufCMessage base;
  char *event_name;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
};
#define CCLIENT_MSG__CUSTOM_GAME_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cclient_msg__custom_game_event__descriptor) \
    , NULL, 0,{0,NULL} }


struct  _CClientMsgClientUIEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_event;
  EClientUIEvent event;
  protobuf_c_boolean has_ent_ehandle;
  uint32_t ent_ehandle;
  protobuf_c_boolean has_client_ehandle;
  uint32_t client_ehandle;
  char *data1;
  char *data2;
};
#define CCLIENT_MSG__CLIENT_UIEVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cclient_msg__client_uievent__descriptor) \
    , 0,ECLIENT_UIEVENT__EClientUIEvent_Invalid, 0,0, 0,0, NULL, NULL }


/* CClientMsgCustomGameEvent methods */
void   cclient_msg__custom_game_event__init
                     (CClientMsgCustomGameEvent         *message);
size_t cclient_msg__custom_game_event__get_packed_size
                     (const CClientMsgCustomGameEvent   *message);
size_t cclient_msg__custom_game_event__pack
                     (const CClientMsgCustomGameEvent   *message,
                      uint8_t             *out);
size_t cclient_msg__custom_game_event__pack_to_buffer
                     (const CClientMsgCustomGameEvent   *message,
                      ProtobufCBuffer     *buffer);
CClientMsgCustomGameEvent *
       cclient_msg__custom_game_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cclient_msg__custom_game_event__free_unpacked
                     (CClientMsgCustomGameEvent *message,
                      ProtobufCAllocator *allocator);
/* CClientMsgClientUIEvent methods */
void   cclient_msg__client_uievent__init
                     (CClientMsgClientUIEvent         *message);
size_t cclient_msg__client_uievent__get_packed_size
                     (const CClientMsgClientUIEvent   *message);
size_t cclient_msg__client_uievent__pack
                     (const CClientMsgClientUIEvent   *message,
                      uint8_t             *out);
size_t cclient_msg__client_uievent__pack_to_buffer
                     (const CClientMsgClientUIEvent   *message,
                      ProtobufCBuffer     *buffer);
CClientMsgClientUIEvent *
       cclient_msg__client_uievent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cclient_msg__client_uievent__free_unpacked
                     (CClientMsgClientUIEvent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CClientMsgCustomGameEvent_Closure)
                 (const CClientMsgCustomGameEvent *message,
                  void *closure_data);
typedef void (*CClientMsgClientUIEvent_Closure)
                 (const CClientMsgClientUIEvent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    ebase_client_messages__descriptor;
extern const ProtobufCEnumDescriptor    eclient_uievent__descriptor;
extern const ProtobufCMessageDescriptor cclient_msg__custom_game_event__descriptor;
extern const ProtobufCMessageDescriptor cclient_msg__client_uievent__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_clientmessages_2eproto__INCLUDED */
