/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "demo.pb-c.h"
void   cdemo_file_header__init
                     (CDemoFileHeader         *message)
{
  static CDemoFileHeader init_value = CDEMO_FILE_HEADER__INIT;
  *message = init_value;
}
size_t cdemo_file_header__get_packed_size
                     (const CDemoFileHeader *message)
{
  assert(message->base.descriptor == &cdemo_file_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_file_header__pack
                     (const CDemoFileHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_file_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_file_header__pack_to_buffer
                     (const CDemoFileHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_file_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoFileHeader *
       cdemo_file_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoFileHeader *)
     protobuf_c_message_unpack (&cdemo_file_header__descriptor,
                                allocator, len, data);
}
void   cdemo_file_header__free_unpacked
                     (CDemoFileHeader *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_file_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cgame_info__cdota_game_info__cplayer_info__init
                     (CGameInfo__CDotaGameInfo__CPlayerInfo         *message)
{
  static CGameInfo__CDotaGameInfo__CPlayerInfo init_value = CGAME_INFO__CDOTA_GAME_INFO__CPLAYER_INFO__INIT;
  *message = init_value;
}
void   cgame_info__cdota_game_info__chero_select_event__init
                     (CGameInfo__CDotaGameInfo__CHeroSelectEvent         *message)
{
  static CGameInfo__CDotaGameInfo__CHeroSelectEvent init_value = CGAME_INFO__CDOTA_GAME_INFO__CHERO_SELECT_EVENT__INIT;
  *message = init_value;
}
void   cgame_info__cdota_game_info__init
                     (CGameInfo__CDotaGameInfo         *message)
{
  static CGameInfo__CDotaGameInfo init_value = CGAME_INFO__CDOTA_GAME_INFO__INIT;
  *message = init_value;
}
void   cgame_info__init
                     (CGameInfo         *message)
{
  static CGameInfo init_value = CGAME_INFO__INIT;
  *message = init_value;
}
size_t cgame_info__get_packed_size
                     (const CGameInfo *message)
{
  assert(message->base.descriptor == &cgame_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cgame_info__pack
                     (const CGameInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cgame_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cgame_info__pack_to_buffer
                     (const CGameInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cgame_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CGameInfo *
       cgame_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CGameInfo *)
     protobuf_c_message_unpack (&cgame_info__descriptor,
                                allocator, len, data);
}
void   cgame_info__free_unpacked
                     (CGameInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cgame_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_file_info__init
                     (CDemoFileInfo         *message)
{
  static CDemoFileInfo init_value = CDEMO_FILE_INFO__INIT;
  *message = init_value;
}
size_t cdemo_file_info__get_packed_size
                     (const CDemoFileInfo *message)
{
  assert(message->base.descriptor == &cdemo_file_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_file_info__pack
                     (const CDemoFileInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_file_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_file_info__pack_to_buffer
                     (const CDemoFileInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_file_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoFileInfo *
       cdemo_file_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoFileInfo *)
     protobuf_c_message_unpack (&cdemo_file_info__descriptor,
                                allocator, len, data);
}
void   cdemo_file_info__free_unpacked
                     (CDemoFileInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_file_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_packet__init
                     (CDemoPacket         *message)
{
  static CDemoPacket init_value = CDEMO_PACKET__INIT;
  *message = init_value;
}
size_t cdemo_packet__get_packed_size
                     (const CDemoPacket *message)
{
  assert(message->base.descriptor == &cdemo_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_packet__pack
                     (const CDemoPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_packet__pack_to_buffer
                     (const CDemoPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoPacket *
       cdemo_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoPacket *)
     protobuf_c_message_unpack (&cdemo_packet__descriptor,
                                allocator, len, data);
}
void   cdemo_packet__free_unpacked
                     (CDemoPacket *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_full_packet__init
                     (CDemoFullPacket         *message)
{
  static CDemoFullPacket init_value = CDEMO_FULL_PACKET__INIT;
  *message = init_value;
}
size_t cdemo_full_packet__get_packed_size
                     (const CDemoFullPacket *message)
{
  assert(message->base.descriptor == &cdemo_full_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_full_packet__pack
                     (const CDemoFullPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_full_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_full_packet__pack_to_buffer
                     (const CDemoFullPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_full_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoFullPacket *
       cdemo_full_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoFullPacket *)
     protobuf_c_message_unpack (&cdemo_full_packet__descriptor,
                                allocator, len, data);
}
void   cdemo_full_packet__free_unpacked
                     (CDemoFullPacket *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_full_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_save_game__init
                     (CDemoSaveGame         *message)
{
  static CDemoSaveGame init_value = CDEMO_SAVE_GAME__INIT;
  *message = init_value;
}
size_t cdemo_save_game__get_packed_size
                     (const CDemoSaveGame *message)
{
  assert(message->base.descriptor == &cdemo_save_game__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_save_game__pack
                     (const CDemoSaveGame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_save_game__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_save_game__pack_to_buffer
                     (const CDemoSaveGame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_save_game__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoSaveGame *
       cdemo_save_game__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoSaveGame *)
     protobuf_c_message_unpack (&cdemo_save_game__descriptor,
                                allocator, len, data);
}
void   cdemo_save_game__free_unpacked
                     (CDemoSaveGame *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_save_game__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_sync_tick__init
                     (CDemoSyncTick         *message)
{
  static CDemoSyncTick init_value = CDEMO_SYNC_TICK__INIT;
  *message = init_value;
}
size_t cdemo_sync_tick__get_packed_size
                     (const CDemoSyncTick *message)
{
  assert(message->base.descriptor == &cdemo_sync_tick__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_sync_tick__pack
                     (const CDemoSyncTick *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_sync_tick__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_sync_tick__pack_to_buffer
                     (const CDemoSyncTick *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_sync_tick__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoSyncTick *
       cdemo_sync_tick__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoSyncTick *)
     protobuf_c_message_unpack (&cdemo_sync_tick__descriptor,
                                allocator, len, data);
}
void   cdemo_sync_tick__free_unpacked
                     (CDemoSyncTick *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_sync_tick__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_console_cmd__init
                     (CDemoConsoleCmd         *message)
{
  static CDemoConsoleCmd init_value = CDEMO_CONSOLE_CMD__INIT;
  *message = init_value;
}
size_t cdemo_console_cmd__get_packed_size
                     (const CDemoConsoleCmd *message)
{
  assert(message->base.descriptor == &cdemo_console_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_console_cmd__pack
                     (const CDemoConsoleCmd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_console_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_console_cmd__pack_to_buffer
                     (const CDemoConsoleCmd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_console_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoConsoleCmd *
       cdemo_console_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoConsoleCmd *)
     protobuf_c_message_unpack (&cdemo_console_cmd__descriptor,
                                allocator, len, data);
}
void   cdemo_console_cmd__free_unpacked
                     (CDemoConsoleCmd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_console_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_send_tables__init
                     (CDemoSendTables         *message)
{
  static CDemoSendTables init_value = CDEMO_SEND_TABLES__INIT;
  *message = init_value;
}
size_t cdemo_send_tables__get_packed_size
                     (const CDemoSendTables *message)
{
  assert(message->base.descriptor == &cdemo_send_tables__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_send_tables__pack
                     (const CDemoSendTables *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_send_tables__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_send_tables__pack_to_buffer
                     (const CDemoSendTables *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_send_tables__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoSendTables *
       cdemo_send_tables__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoSendTables *)
     protobuf_c_message_unpack (&cdemo_send_tables__descriptor,
                                allocator, len, data);
}
void   cdemo_send_tables__free_unpacked
                     (CDemoSendTables *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_send_tables__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_class_info__class_t__init
                     (CDemoClassInfo__ClassT         *message)
{
  static CDemoClassInfo__ClassT init_value = CDEMO_CLASS_INFO__CLASS_T__INIT;
  *message = init_value;
}
void   cdemo_class_info__init
                     (CDemoClassInfo         *message)
{
  static CDemoClassInfo init_value = CDEMO_CLASS_INFO__INIT;
  *message = init_value;
}
size_t cdemo_class_info__get_packed_size
                     (const CDemoClassInfo *message)
{
  assert(message->base.descriptor == &cdemo_class_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_class_info__pack
                     (const CDemoClassInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_class_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_class_info__pack_to_buffer
                     (const CDemoClassInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_class_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoClassInfo *
       cdemo_class_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoClassInfo *)
     protobuf_c_message_unpack (&cdemo_class_info__descriptor,
                                allocator, len, data);
}
void   cdemo_class_info__free_unpacked
                     (CDemoClassInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_class_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_custom_data__init
                     (CDemoCustomData         *message)
{
  static CDemoCustomData init_value = CDEMO_CUSTOM_DATA__INIT;
  *message = init_value;
}
size_t cdemo_custom_data__get_packed_size
                     (const CDemoCustomData *message)
{
  assert(message->base.descriptor == &cdemo_custom_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_custom_data__pack
                     (const CDemoCustomData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_custom_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_custom_data__pack_to_buffer
                     (const CDemoCustomData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_custom_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoCustomData *
       cdemo_custom_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoCustomData *)
     protobuf_c_message_unpack (&cdemo_custom_data__descriptor,
                                allocator, len, data);
}
void   cdemo_custom_data__free_unpacked
                     (CDemoCustomData *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_custom_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_custom_data_callbacks__init
                     (CDemoCustomDataCallbacks         *message)
{
  static CDemoCustomDataCallbacks init_value = CDEMO_CUSTOM_DATA_CALLBACKS__INIT;
  *message = init_value;
}
size_t cdemo_custom_data_callbacks__get_packed_size
                     (const CDemoCustomDataCallbacks *message)
{
  assert(message->base.descriptor == &cdemo_custom_data_callbacks__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_custom_data_callbacks__pack
                     (const CDemoCustomDataCallbacks *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_custom_data_callbacks__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_custom_data_callbacks__pack_to_buffer
                     (const CDemoCustomDataCallbacks *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_custom_data_callbacks__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoCustomDataCallbacks *
       cdemo_custom_data_callbacks__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoCustomDataCallbacks *)
     protobuf_c_message_unpack (&cdemo_custom_data_callbacks__descriptor,
                                allocator, len, data);
}
void   cdemo_custom_data_callbacks__free_unpacked
                     (CDemoCustomDataCallbacks *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_custom_data_callbacks__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_string_tables__items_t__init
                     (CDemoStringTables__ItemsT         *message)
{
  static CDemoStringTables__ItemsT init_value = CDEMO_STRING_TABLES__ITEMS_T__INIT;
  *message = init_value;
}
void   cdemo_string_tables__table_t__init
                     (CDemoStringTables__TableT         *message)
{
  static CDemoStringTables__TableT init_value = CDEMO_STRING_TABLES__TABLE_T__INIT;
  *message = init_value;
}
void   cdemo_string_tables__init
                     (CDemoStringTables         *message)
{
  static CDemoStringTables init_value = CDEMO_STRING_TABLES__INIT;
  *message = init_value;
}
size_t cdemo_string_tables__get_packed_size
                     (const CDemoStringTables *message)
{
  assert(message->base.descriptor == &cdemo_string_tables__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_string_tables__pack
                     (const CDemoStringTables *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_string_tables__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_string_tables__pack_to_buffer
                     (const CDemoStringTables *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_string_tables__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoStringTables *
       cdemo_string_tables__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoStringTables *)
     protobuf_c_message_unpack (&cdemo_string_tables__descriptor,
                                allocator, len, data);
}
void   cdemo_string_tables__free_unpacked
                     (CDemoStringTables *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_string_tables__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_stop__init
                     (CDemoStop         *message)
{
  static CDemoStop init_value = CDEMO_STOP__INIT;
  *message = init_value;
}
size_t cdemo_stop__get_packed_size
                     (const CDemoStop *message)
{
  assert(message->base.descriptor == &cdemo_stop__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_stop__pack
                     (const CDemoStop *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_stop__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_stop__pack_to_buffer
                     (const CDemoStop *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_stop__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoStop *
       cdemo_stop__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoStop *)
     protobuf_c_message_unpack (&cdemo_stop__descriptor,
                                allocator, len, data);
}
void   cdemo_stop__free_unpacked
                     (CDemoStop *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_stop__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_user_cmd__init
                     (CDemoUserCmd         *message)
{
  static CDemoUserCmd init_value = CDEMO_USER_CMD__INIT;
  *message = init_value;
}
size_t cdemo_user_cmd__get_packed_size
                     (const CDemoUserCmd *message)
{
  assert(message->base.descriptor == &cdemo_user_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_user_cmd__pack
                     (const CDemoUserCmd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_user_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_user_cmd__pack_to_buffer
                     (const CDemoUserCmd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_user_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoUserCmd *
       cdemo_user_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoUserCmd *)
     protobuf_c_message_unpack (&cdemo_user_cmd__descriptor,
                                allocator, len, data);
}
void   cdemo_user_cmd__free_unpacked
                     (CDemoUserCmd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_user_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdemo_spawn_groups__init
                     (CDemoSpawnGroups         *message)
{
  static CDemoSpawnGroups init_value = CDEMO_SPAWN_GROUPS__INIT;
  *message = init_value;
}
size_t cdemo_spawn_groups__get_packed_size
                     (const CDemoSpawnGroups *message)
{
  assert(message->base.descriptor == &cdemo_spawn_groups__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdemo_spawn_groups__pack
                     (const CDemoSpawnGroups *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdemo_spawn_groups__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdemo_spawn_groups__pack_to_buffer
                     (const CDemoSpawnGroups *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdemo_spawn_groups__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDemoSpawnGroups *
       cdemo_spawn_groups__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDemoSpawnGroups *)
     protobuf_c_message_unpack (&cdemo_spawn_groups__descriptor,
                                allocator, len, data);
}
void   cdemo_spawn_groups__free_unpacked
                     (CDemoSpawnGroups *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdemo_spawn_groups__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cdemo_file_header__field_descriptors[10] =
{
  {
    "demo_file_stamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoFileHeader, demo_file_stamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_protocol",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoFileHeader, has_network_protocol),
    offsetof(CDemoFileHeader, network_protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoFileHeader, server_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_name",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoFileHeader, client_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_name",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoFileHeader, map_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_directory",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoFileHeader, game_directory),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fullpackets_version",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoFileHeader, has_fullpackets_version),
    offsetof(CDemoFileHeader, fullpackets_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allow_clientside_entities",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CDemoFileHeader, has_allow_clientside_entities),
    offsetof(CDemoFileHeader, allow_clientside_entities),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allow_clientside_particles",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CDemoFileHeader, has_allow_clientside_particles),
    offsetof(CDemoFileHeader, allow_clientside_particles),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addons",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoFileHeader, addons),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_file_header__field_indices_by_name[] = {
  9,   /* field[9] = addons */
  7,   /* field[7] = allow_clientside_entities */
  8,   /* field[8] = allow_clientside_particles */
  3,   /* field[3] = client_name */
  0,   /* field[0] = demo_file_stamp */
  6,   /* field[6] = fullpackets_version */
  5,   /* field[5] = game_directory */
  4,   /* field[4] = map_name */
  1,   /* field[1] = network_protocol */
  2,   /* field[2] = server_name */
};
static const ProtobufCIntRange cdemo_file_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor cdemo_file_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoFileHeader",
  "CDemoFileHeader",
  "CDemoFileHeader",
  "",
  sizeof(CDemoFileHeader),
  10,
  cdemo_file_header__field_descriptors,
  cdemo_file_header__field_indices_by_name,
  1,  cdemo_file_header__number_ranges,
  (ProtobufCMessageInit) cdemo_file_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cgame_info__cdota_game_info__cplayer_info__field_descriptors[5] =
{
  {
    "hero_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CGameInfo__CDotaGameInfo__CPlayerInfo, hero_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CGameInfo__CDotaGameInfo__CPlayerInfo, player_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_fake_client",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CGameInfo__CDotaGameInfo__CPlayerInfo, has_is_fake_client),
    offsetof(CGameInfo__CDotaGameInfo__CPlayerInfo, is_fake_client),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steamid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CGameInfo__CDotaGameInfo__CPlayerInfo, has_steamid),
    offsetof(CGameInfo__CDotaGameInfo__CPlayerInfo, steamid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_team",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CGameInfo__CDotaGameInfo__CPlayerInfo, has_game_team),
    offsetof(CGameInfo__CDotaGameInfo__CPlayerInfo, game_team),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cgame_info__cdota_game_info__cplayer_info__field_indices_by_name[] = {
  4,   /* field[4] = game_team */
  0,   /* field[0] = hero_name */
  2,   /* field[2] = is_fake_client */
  1,   /* field[1] = player_name */
  3,   /* field[3] = steamid */
};
static const ProtobufCIntRange cgame_info__cdota_game_info__cplayer_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor cgame_info__cdota_game_info__cplayer_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CGameInfo.CDotaGameInfo.CPlayerInfo",
  "CPlayerInfo",
  "CGameInfo__CDotaGameInfo__CPlayerInfo",
  "",
  sizeof(CGameInfo__CDotaGameInfo__CPlayerInfo),
  5,
  cgame_info__cdota_game_info__cplayer_info__field_descriptors,
  cgame_info__cdota_game_info__cplayer_info__field_indices_by_name,
  1,  cgame_info__cdota_game_info__cplayer_info__number_ranges,
  (ProtobufCMessageInit) cgame_info__cdota_game_info__cplayer_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cgame_info__cdota_game_info__chero_select_event__field_descriptors[3] =
{
  {
    "is_pick",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CGameInfo__CDotaGameInfo__CHeroSelectEvent, has_is_pick),
    offsetof(CGameInfo__CDotaGameInfo__CHeroSelectEvent, is_pick),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "team",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CGameInfo__CDotaGameInfo__CHeroSelectEvent, has_team),
    offsetof(CGameInfo__CDotaGameInfo__CHeroSelectEvent, team),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hero_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CGameInfo__CDotaGameInfo__CHeroSelectEvent, has_hero_id),
    offsetof(CGameInfo__CDotaGameInfo__CHeroSelectEvent, hero_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cgame_info__cdota_game_info__chero_select_event__field_indices_by_name[] = {
  2,   /* field[2] = hero_id */
  0,   /* field[0] = is_pick */
  1,   /* field[1] = team */
};
static const ProtobufCIntRange cgame_info__cdota_game_info__chero_select_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cgame_info__cdota_game_info__chero_select_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CGameInfo.CDotaGameInfo.CHeroSelectEvent",
  "CHeroSelectEvent",
  "CGameInfo__CDotaGameInfo__CHeroSelectEvent",
  "",
  sizeof(CGameInfo__CDotaGameInfo__CHeroSelectEvent),
  3,
  cgame_info__cdota_game_info__chero_select_event__field_descriptors,
  cgame_info__cdota_game_info__chero_select_event__field_indices_by_name,
  1,  cgame_info__cdota_game_info__chero_select_event__number_ranges,
  (ProtobufCMessageInit) cgame_info__cdota_game_info__chero_select_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cgame_info__cdota_game_info__field_descriptors[11] =
{
  {
    "match_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CGameInfo__CDotaGameInfo, has_match_id),
    offsetof(CGameInfo__CDotaGameInfo, match_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_mode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CGameInfo__CDotaGameInfo, has_game_mode),
    offsetof(CGameInfo__CDotaGameInfo, game_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_winner",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CGameInfo__CDotaGameInfo, has_game_winner),
    offsetof(CGameInfo__CDotaGameInfo, game_winner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_info",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CGameInfo__CDotaGameInfo, n_player_info),
    offsetof(CGameInfo__CDotaGameInfo, player_info),
    &cgame_info__cdota_game_info__cplayer_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leagueid",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CGameInfo__CDotaGameInfo, has_leagueid),
    offsetof(CGameInfo__CDotaGameInfo, leagueid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "picks_bans",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CGameInfo__CDotaGameInfo, n_picks_bans),
    offsetof(CGameInfo__CDotaGameInfo, picks_bans),
    &cgame_info__cdota_game_info__chero_select_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radiant_team_id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CGameInfo__CDotaGameInfo, has_radiant_team_id),
    offsetof(CGameInfo__CDotaGameInfo, radiant_team_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dire_team_id",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CGameInfo__CDotaGameInfo, has_dire_team_id),
    offsetof(CGameInfo__CDotaGameInfo, dire_team_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radiant_team_tag",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CGameInfo__CDotaGameInfo, radiant_team_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dire_team_tag",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CGameInfo__CDotaGameInfo, dire_team_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_time",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CGameInfo__CDotaGameInfo, has_end_time),
    offsetof(CGameInfo__CDotaGameInfo, end_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cgame_info__cdota_game_info__field_indices_by_name[] = {
  7,   /* field[7] = dire_team_id */
  9,   /* field[9] = dire_team_tag */
  10,   /* field[10] = end_time */
  1,   /* field[1] = game_mode */
  2,   /* field[2] = game_winner */
  4,   /* field[4] = leagueid */
  0,   /* field[0] = match_id */
  5,   /* field[5] = picks_bans */
  3,   /* field[3] = player_info */
  6,   /* field[6] = radiant_team_id */
  8,   /* field[8] = radiant_team_tag */
};
static const ProtobufCIntRange cgame_info__cdota_game_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor cgame_info__cdota_game_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CGameInfo.CDotaGameInfo",
  "CDotaGameInfo",
  "CGameInfo__CDotaGameInfo",
  "",
  sizeof(CGameInfo__CDotaGameInfo),
  11,
  cgame_info__cdota_game_info__field_descriptors,
  cgame_info__cdota_game_info__field_indices_by_name,
  1,  cgame_info__cdota_game_info__number_ranges,
  (ProtobufCMessageInit) cgame_info__cdota_game_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cgame_info__field_descriptors[1] =
{
  {
    "dota",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CGameInfo, dota),
    &cgame_info__cdota_game_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cgame_info__field_indices_by_name[] = {
  0,   /* field[0] = dota */
};
static const ProtobufCIntRange cgame_info__number_ranges[1 + 1] =
{
  { 4, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cgame_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CGameInfo",
  "CGameInfo",
  "CGameInfo",
  "",
  sizeof(CGameInfo),
  1,
  cgame_info__field_descriptors,
  cgame_info__field_indices_by_name,
  1,  cgame_info__number_ranges,
  (ProtobufCMessageInit) cgame_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_file_info__field_descriptors[4] =
{
  {
    "playback_time",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDemoFileInfo, has_playback_time),
    offsetof(CDemoFileInfo, playback_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "playback_ticks",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoFileInfo, has_playback_ticks),
    offsetof(CDemoFileInfo, playback_ticks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "playback_frames",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoFileInfo, has_playback_frames),
    offsetof(CDemoFileInfo, playback_frames),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_info",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CDemoFileInfo, game_info),
    &cgame_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_file_info__field_indices_by_name[] = {
  3,   /* field[3] = game_info */
  2,   /* field[2] = playback_frames */
  1,   /* field[1] = playback_ticks */
  0,   /* field[0] = playback_time */
};
static const ProtobufCIntRange cdemo_file_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cdemo_file_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoFileInfo",
  "CDemoFileInfo",
  "CDemoFileInfo",
  "",
  sizeof(CDemoFileInfo),
  4,
  cdemo_file_info__field_descriptors,
  cdemo_file_info__field_indices_by_name,
  1,  cdemo_file_info__number_ranges,
  (ProtobufCMessageInit) cdemo_file_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_packet__field_descriptors[3] =
{
  {
    "sequence_in",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoPacket, has_sequence_in),
    offsetof(CDemoPacket, sequence_in),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_out_ack",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoPacket, has_sequence_out_ack),
    offsetof(CDemoPacket, sequence_out_ack),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CDemoPacket, has_data),
    offsetof(CDemoPacket, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_packet__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = sequence_in */
  1,   /* field[1] = sequence_out_ack */
};
static const ProtobufCIntRange cdemo_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cdemo_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoPacket",
  "CDemoPacket",
  "CDemoPacket",
  "",
  sizeof(CDemoPacket),
  3,
  cdemo_packet__field_descriptors,
  cdemo_packet__field_indices_by_name,
  1,  cdemo_packet__number_ranges,
  (ProtobufCMessageInit) cdemo_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_full_packet__field_descriptors[2] =
{
  {
    "string_table",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CDemoFullPacket, string_table),
    &cdemo_string_tables__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CDemoFullPacket, packet),
    &cdemo_packet__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_full_packet__field_indices_by_name[] = {
  1,   /* field[1] = packet */
  0,   /* field[0] = string_table */
};
static const ProtobufCIntRange cdemo_full_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cdemo_full_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoFullPacket",
  "CDemoFullPacket",
  "CDemoFullPacket",
  "",
  sizeof(CDemoFullPacket),
  2,
  cdemo_full_packet__field_descriptors,
  cdemo_full_packet__field_indices_by_name,
  1,  cdemo_full_packet__number_ranges,
  (ProtobufCMessageInit) cdemo_full_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_save_game__field_descriptors[4] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CDemoSaveGame, has_data),
    offsetof(CDemoSaveGame, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steam_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(CDemoSaveGame, has_steam_id),
    offsetof(CDemoSaveGame, steam_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(CDemoSaveGame, has_signature),
    offsetof(CDemoSaveGame, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoSaveGame, has_version),
    offsetof(CDemoSaveGame, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_save_game__field_indices_by_name[] = {
  0,   /* field[0] = data */
  2,   /* field[2] = signature */
  1,   /* field[1] = steam_id */
  3,   /* field[3] = version */
};
static const ProtobufCIntRange cdemo_save_game__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cdemo_save_game__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoSaveGame",
  "CDemoSaveGame",
  "CDemoSaveGame",
  "",
  sizeof(CDemoSaveGame),
  4,
  cdemo_save_game__field_descriptors,
  cdemo_save_game__field_indices_by_name,
  1,  cdemo_save_game__number_ranges,
  (ProtobufCMessageInit) cdemo_save_game__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define cdemo_sync_tick__field_descriptors NULL
#define cdemo_sync_tick__field_indices_by_name NULL
#define cdemo_sync_tick__number_ranges NULL
const ProtobufCMessageDescriptor cdemo_sync_tick__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoSyncTick",
  "CDemoSyncTick",
  "CDemoSyncTick",
  "",
  sizeof(CDemoSyncTick),
  0,
  cdemo_sync_tick__field_descriptors,
  cdemo_sync_tick__field_indices_by_name,
  0,  cdemo_sync_tick__number_ranges,
  (ProtobufCMessageInit) cdemo_sync_tick__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_console_cmd__field_descriptors[1] =
{
  {
    "cmdstring",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoConsoleCmd, cmdstring),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_console_cmd__field_indices_by_name[] = {
  0,   /* field[0] = cmdstring */
};
static const ProtobufCIntRange cdemo_console_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cdemo_console_cmd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoConsoleCmd",
  "CDemoConsoleCmd",
  "CDemoConsoleCmd",
  "",
  sizeof(CDemoConsoleCmd),
  1,
  cdemo_console_cmd__field_descriptors,
  cdemo_console_cmd__field_indices_by_name,
  1,  cdemo_console_cmd__number_ranges,
  (ProtobufCMessageInit) cdemo_console_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_send_tables__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CDemoSendTables, has_data),
    offsetof(CDemoSendTables, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_send_tables__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange cdemo_send_tables__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cdemo_send_tables__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoSendTables",
  "CDemoSendTables",
  "CDemoSendTables",
  "",
  sizeof(CDemoSendTables),
  1,
  cdemo_send_tables__field_descriptors,
  cdemo_send_tables__field_indices_by_name,
  1,  cdemo_send_tables__number_ranges,
  (ProtobufCMessageInit) cdemo_send_tables__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_class_info__class_t__field_descriptors[3] =
{
  {
    "class_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoClassInfo__ClassT, has_class_id),
    offsetof(CDemoClassInfo__ClassT, class_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoClassInfo__ClassT, network_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoClassInfo__ClassT, table_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_class_info__class_t__field_indices_by_name[] = {
  0,   /* field[0] = class_id */
  1,   /* field[1] = network_name */
  2,   /* field[2] = table_name */
};
static const ProtobufCIntRange cdemo_class_info__class_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cdemo_class_info__class_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoClassInfo.class_t",
  "ClassT",
  "CDemoClassInfo__ClassT",
  "",
  sizeof(CDemoClassInfo__ClassT),
  3,
  cdemo_class_info__class_t__field_descriptors,
  cdemo_class_info__class_t__field_indices_by_name,
  1,  cdemo_class_info__class_t__number_ranges,
  (ProtobufCMessageInit) cdemo_class_info__class_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_class_info__field_descriptors[1] =
{
  {
    "classes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDemoClassInfo, n_classes),
    offsetof(CDemoClassInfo, classes),
    &cdemo_class_info__class_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_class_info__field_indices_by_name[] = {
  0,   /* field[0] = classes */
};
static const ProtobufCIntRange cdemo_class_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cdemo_class_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoClassInfo",
  "CDemoClassInfo",
  "CDemoClassInfo",
  "",
  sizeof(CDemoClassInfo),
  1,
  cdemo_class_info__field_descriptors,
  cdemo_class_info__field_indices_by_name,
  1,  cdemo_class_info__number_ranges,
  (ProtobufCMessageInit) cdemo_class_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_custom_data__field_descriptors[2] =
{
  {
    "callback_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoCustomData, has_callback_index),
    offsetof(CDemoCustomData, callback_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CDemoCustomData, has_data),
    offsetof(CDemoCustomData, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_custom_data__field_indices_by_name[] = {
  0,   /* field[0] = callback_index */
  1,   /* field[1] = data */
};
static const ProtobufCIntRange cdemo_custom_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cdemo_custom_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoCustomData",
  "CDemoCustomData",
  "CDemoCustomData",
  "",
  sizeof(CDemoCustomData),
  2,
  cdemo_custom_data__field_descriptors,
  cdemo_custom_data__field_indices_by_name,
  1,  cdemo_custom_data__number_ranges,
  (ProtobufCMessageInit) cdemo_custom_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_custom_data_callbacks__field_descriptors[1] =
{
  {
    "save_id",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(CDemoCustomDataCallbacks, n_save_id),
    offsetof(CDemoCustomDataCallbacks, save_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_custom_data_callbacks__field_indices_by_name[] = {
  0,   /* field[0] = save_id */
};
static const ProtobufCIntRange cdemo_custom_data_callbacks__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cdemo_custom_data_callbacks__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoCustomDataCallbacks",
  "CDemoCustomDataCallbacks",
  "CDemoCustomDataCallbacks",
  "",
  sizeof(CDemoCustomDataCallbacks),
  1,
  cdemo_custom_data_callbacks__field_descriptors,
  cdemo_custom_data_callbacks__field_indices_by_name,
  1,  cdemo_custom_data_callbacks__number_ranges,
  (ProtobufCMessageInit) cdemo_custom_data_callbacks__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_string_tables__items_t__field_descriptors[2] =
{
  {
    "str",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoStringTables__ItemsT, str),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CDemoStringTables__ItemsT, has_data),
    offsetof(CDemoStringTables__ItemsT, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_string_tables__items_t__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = str */
};
static const ProtobufCIntRange cdemo_string_tables__items_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cdemo_string_tables__items_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoStringTables.items_t",
  "ItemsT",
  "CDemoStringTables__ItemsT",
  "",
  sizeof(CDemoStringTables__ItemsT),
  2,
  cdemo_string_tables__items_t__field_descriptors,
  cdemo_string_tables__items_t__field_indices_by_name,
  1,  cdemo_string_tables__items_t__number_ranges,
  (ProtobufCMessageInit) cdemo_string_tables__items_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_string_tables__table_t__field_descriptors[4] =
{
  {
    "table_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDemoStringTables__TableT, table_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDemoStringTables__TableT, n_items),
    offsetof(CDemoStringTables__TableT, items),
    &cdemo_string_tables__items_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items_clientside",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDemoStringTables__TableT, n_items_clientside),
    offsetof(CDemoStringTables__TableT, items_clientside),
    &cdemo_string_tables__items_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_flags",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoStringTables__TableT, has_table_flags),
    offsetof(CDemoStringTables__TableT, table_flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_string_tables__table_t__field_indices_by_name[] = {
  1,   /* field[1] = items */
  2,   /* field[2] = items_clientside */
  3,   /* field[3] = table_flags */
  0,   /* field[0] = table_name */
};
static const ProtobufCIntRange cdemo_string_tables__table_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cdemo_string_tables__table_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoStringTables.table_t",
  "TableT",
  "CDemoStringTables__TableT",
  "",
  sizeof(CDemoStringTables__TableT),
  4,
  cdemo_string_tables__table_t__field_descriptors,
  cdemo_string_tables__table_t__field_indices_by_name,
  1,  cdemo_string_tables__table_t__number_ranges,
  (ProtobufCMessageInit) cdemo_string_tables__table_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_string_tables__field_descriptors[1] =
{
  {
    "tables",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDemoStringTables, n_tables),
    offsetof(CDemoStringTables, tables),
    &cdemo_string_tables__table_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_string_tables__field_indices_by_name[] = {
  0,   /* field[0] = tables */
};
static const ProtobufCIntRange cdemo_string_tables__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cdemo_string_tables__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoStringTables",
  "CDemoStringTables",
  "CDemoStringTables",
  "",
  sizeof(CDemoStringTables),
  1,
  cdemo_string_tables__field_descriptors,
  cdemo_string_tables__field_indices_by_name,
  1,  cdemo_string_tables__number_ranges,
  (ProtobufCMessageInit) cdemo_string_tables__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define cdemo_stop__field_descriptors NULL
#define cdemo_stop__field_indices_by_name NULL
#define cdemo_stop__number_ranges NULL
const ProtobufCMessageDescriptor cdemo_stop__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoStop",
  "CDemoStop",
  "CDemoStop",
  "",
  sizeof(CDemoStop),
  0,
  cdemo_stop__field_descriptors,
  cdemo_stop__field_indices_by_name,
  0,  cdemo_stop__number_ranges,
  (ProtobufCMessageInit) cdemo_stop__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_user_cmd__field_descriptors[2] =
{
  {
    "cmd_number",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDemoUserCmd, has_cmd_number),
    offsetof(CDemoUserCmd, cmd_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CDemoUserCmd, has_data),
    offsetof(CDemoUserCmd, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_user_cmd__field_indices_by_name[] = {
  0,   /* field[0] = cmd_number */
  1,   /* field[1] = data */
};
static const ProtobufCIntRange cdemo_user_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cdemo_user_cmd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoUserCmd",
  "CDemoUserCmd",
  "CDemoUserCmd",
  "",
  sizeof(CDemoUserCmd),
  2,
  cdemo_user_cmd__field_descriptors,
  cdemo_user_cmd__field_indices_by_name,
  1,  cdemo_user_cmd__number_ranges,
  (ProtobufCMessageInit) cdemo_user_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdemo_spawn_groups__field_descriptors[1] =
{
  {
    "msgs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CDemoSpawnGroups, n_msgs),
    offsetof(CDemoSpawnGroups, msgs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdemo_spawn_groups__field_indices_by_name[] = {
  0,   /* field[0] = msgs */
};
static const ProtobufCIntRange cdemo_spawn_groups__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cdemo_spawn_groups__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDemoSpawnGroups",
  "CDemoSpawnGroups",
  "CDemoSpawnGroups",
  "",
  sizeof(CDemoSpawnGroups),
  1,
  cdemo_spawn_groups__field_descriptors,
  cdemo_spawn_groups__field_indices_by_name,
  1,  cdemo_spawn_groups__number_ranges,
  (ProtobufCMessageInit) cdemo_spawn_groups__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue edemo_commands__enum_values_by_number[19] =
{
  { "DEM_Error", "EDEMO_COMMANDS__DEM_Error", -1 },
  { "DEM_Stop", "EDEMO_COMMANDS__DEM_Stop", 0 },
  { "DEM_FileHeader", "EDEMO_COMMANDS__DEM_FileHeader", 1 },
  { "DEM_FileInfo", "EDEMO_COMMANDS__DEM_FileInfo", 2 },
  { "DEM_SyncTick", "EDEMO_COMMANDS__DEM_SyncTick", 3 },
  { "DEM_SendTables", "EDEMO_COMMANDS__DEM_SendTables", 4 },
  { "DEM_ClassInfo", "EDEMO_COMMANDS__DEM_ClassInfo", 5 },
  { "DEM_StringTables", "EDEMO_COMMANDS__DEM_StringTables", 6 },
  { "DEM_Packet", "EDEMO_COMMANDS__DEM_Packet", 7 },
  { "DEM_SignonPacket", "EDEMO_COMMANDS__DEM_SignonPacket", 8 },
  { "DEM_ConsoleCmd", "EDEMO_COMMANDS__DEM_ConsoleCmd", 9 },
  { "DEM_CustomData", "EDEMO_COMMANDS__DEM_CustomData", 10 },
  { "DEM_CustomDataCallbacks", "EDEMO_COMMANDS__DEM_CustomDataCallbacks", 11 },
  { "DEM_UserCmd", "EDEMO_COMMANDS__DEM_UserCmd", 12 },
  { "DEM_FullPacket", "EDEMO_COMMANDS__DEM_FullPacket", 13 },
  { "DEM_SaveGame", "EDEMO_COMMANDS__DEM_SaveGame", 14 },
  { "DEM_SpawnGroups", "EDEMO_COMMANDS__DEM_SpawnGroups", 15 },
  { "DEM_Max", "EDEMO_COMMANDS__DEM_Max", 16 },
  { "DEM_IsCompressed", "EDEMO_COMMANDS__DEM_IsCompressed", 64 },
};
static const ProtobufCIntRange edemo_commands__value_ranges[] = {
{-1, 0},{64, 18},{0, 19}
};
static const ProtobufCEnumValueIndex edemo_commands__enum_values_by_name[19] =
{
  { "DEM_ClassInfo", 6 },
  { "DEM_ConsoleCmd", 10 },
  { "DEM_CustomData", 11 },
  { "DEM_CustomDataCallbacks", 12 },
  { "DEM_Error", 0 },
  { "DEM_FileHeader", 2 },
  { "DEM_FileInfo", 3 },
  { "DEM_FullPacket", 14 },
  { "DEM_IsCompressed", 18 },
  { "DEM_Max", 17 },
  { "DEM_Packet", 8 },
  { "DEM_SaveGame", 15 },
  { "DEM_SendTables", 5 },
  { "DEM_SignonPacket", 9 },
  { "DEM_SpawnGroups", 16 },
  { "DEM_Stop", 1 },
  { "DEM_StringTables", 7 },
  { "DEM_SyncTick", 4 },
  { "DEM_UserCmd", 13 },
};
const ProtobufCEnumDescriptor edemo_commands__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EDemoCommands",
  "EDemoCommands",
  "EDemoCommands",
  "",
  19,
  edemo_commands__enum_values_by_number,
  19,
  edemo_commands__enum_values_by_name,
  2,
  edemo_commands__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
