/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dota_match_metadata.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dota_match_metadata.pb-c.h"
void   cdotamatch_metadata_file__init
                     (CDOTAMatchMetadataFile         *message)
{
  static CDOTAMatchMetadataFile init_value = CDOTAMATCH_METADATA_FILE__INIT;
  *message = init_value;
}
size_t cdotamatch_metadata_file__get_packed_size
                     (const CDOTAMatchMetadataFile *message)
{
  assert(message->base.descriptor == &cdotamatch_metadata_file__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdotamatch_metadata_file__pack
                     (const CDOTAMatchMetadataFile *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdotamatch_metadata_file__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdotamatch_metadata_file__pack_to_buffer
                     (const CDOTAMatchMetadataFile *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdotamatch_metadata_file__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDOTAMatchMetadataFile *
       cdotamatch_metadata_file__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDOTAMatchMetadataFile *)
     protobuf_c_message_unpack (&cdotamatch_metadata_file__descriptor,
                                allocator, len, data);
}
void   cdotamatch_metadata_file__free_unpacked
                     (CDOTAMatchMetadataFile *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdotamatch_metadata_file__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdotamatch_metadata__team__player_kill__init
                     (CDOTAMatchMetadata__Team__PlayerKill         *message)
{
  static CDOTAMatchMetadata__Team__PlayerKill init_value = CDOTAMATCH_METADATA__TEAM__PLAYER_KILL__INIT;
  *message = init_value;
}
void   cdotamatch_metadata__team__item_purchase__init
                     (CDOTAMatchMetadata__Team__ItemPurchase         *message)
{
  static CDOTAMatchMetadata__Team__ItemPurchase init_value = CDOTAMATCH_METADATA__TEAM__ITEM_PURCHASE__INIT;
  *message = init_value;
}
void   cdotamatch_metadata__team__player__init
                     (CDOTAMatchMetadata__Team__Player         *message)
{
  static CDOTAMatchMetadata__Team__Player init_value = CDOTAMATCH_METADATA__TEAM__PLAYER__INIT;
  *message = init_value;
}
void   cdotamatch_metadata__team__init
                     (CDOTAMatchMetadata__Team         *message)
{
  static CDOTAMatchMetadata__Team init_value = CDOTAMATCH_METADATA__TEAM__INIT;
  *message = init_value;
}
void   cdotamatch_metadata__init
                     (CDOTAMatchMetadata         *message)
{
  static CDOTAMatchMetadata init_value = CDOTAMATCH_METADATA__INIT;
  *message = init_value;
}
size_t cdotamatch_metadata__get_packed_size
                     (const CDOTAMatchMetadata *message)
{
  assert(message->base.descriptor == &cdotamatch_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdotamatch_metadata__pack
                     (const CDOTAMatchMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdotamatch_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdotamatch_metadata__pack_to_buffer
                     (const CDOTAMatchMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdotamatch_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDOTAMatchMetadata *
       cdotamatch_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDOTAMatchMetadata *)
     protobuf_c_message_unpack (&cdotamatch_metadata__descriptor,
                                allocator, len, data);
}
void   cdotamatch_metadata__free_unpacked
                     (CDOTAMatchMetadata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdotamatch_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdotamatch_private_metadata__team__player__init
                     (CDOTAMatchPrivateMetadata__Team__Player         *message)
{
  static CDOTAMatchPrivateMetadata__Team__Player init_value = CDOTAMATCH_PRIVATE_METADATA__TEAM__PLAYER__INIT;
  *message = init_value;
}
void   cdotamatch_private_metadata__team__init
                     (CDOTAMatchPrivateMetadata__Team         *message)
{
  static CDOTAMatchPrivateMetadata__Team init_value = CDOTAMATCH_PRIVATE_METADATA__TEAM__INIT;
  *message = init_value;
}
void   cdotamatch_private_metadata__init
                     (CDOTAMatchPrivateMetadata         *message)
{
  static CDOTAMatchPrivateMetadata init_value = CDOTAMATCH_PRIVATE_METADATA__INIT;
  *message = init_value;
}
size_t cdotamatch_private_metadata__get_packed_size
                     (const CDOTAMatchPrivateMetadata *message)
{
  assert(message->base.descriptor == &cdotamatch_private_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdotamatch_private_metadata__pack
                     (const CDOTAMatchPrivateMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdotamatch_private_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdotamatch_private_metadata__pack_to_buffer
                     (const CDOTAMatchPrivateMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdotamatch_private_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDOTAMatchPrivateMetadata *
       cdotamatch_private_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDOTAMatchPrivateMetadata *)
     protobuf_c_message_unpack (&cdotamatch_private_metadata__descriptor,
                                allocator, len, data);
}
void   cdotamatch_private_metadata__free_unpacked
                     (CDOTAMatchPrivateMetadata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdotamatch_private_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cdotamatch_metadata_file__field_descriptors[4] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CDOTAMatchMetadataFile, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(CDOTAMatchMetadataFile, match_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CDOTAMatchMetadataFile, metadata),
    &cdotamatch_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_metadata",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CDOTAMatchMetadataFile, has_private_metadata),
    offsetof(CDOTAMatchMetadataFile, private_metadata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotamatch_metadata_file__field_indices_by_name[] = {
  1,   /* field[1] = match_id */
  2,   /* field[2] = metadata */
  3,   /* field[3] = private_metadata */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange cdotamatch_metadata_file__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cdotamatch_metadata_file__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTAMatchMetadataFile",
  "CDOTAMatchMetadataFile",
  "CDOTAMatchMetadataFile",
  "",
  sizeof(CDOTAMatchMetadataFile),
  4,
  cdotamatch_metadata_file__field_descriptors,
  cdotamatch_metadata_file__field_indices_by_name,
  2,  cdotamatch_metadata_file__number_ranges,
  (ProtobufCMessageInit) cdotamatch_metadata_file__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotamatch_metadata__team__player_kill__field_descriptors[2] =
{
  {
    "victim_slot",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__PlayerKill, has_victim_slot),
    offsetof(CDOTAMatchMetadata__Team__PlayerKill, victim_slot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__PlayerKill, has_count),
    offsetof(CDOTAMatchMetadata__Team__PlayerKill, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotamatch_metadata__team__player_kill__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = victim_slot */
};
static const ProtobufCIntRange cdotamatch_metadata__team__player_kill__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cdotamatch_metadata__team__player_kill__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTAMatchMetadata.Team.PlayerKill",
  "PlayerKill",
  "CDOTAMatchMetadata__Team__PlayerKill",
  "",
  sizeof(CDOTAMatchMetadata__Team__PlayerKill),
  2,
  cdotamatch_metadata__team__player_kill__field_descriptors,
  cdotamatch_metadata__team__player_kill__field_indices_by_name,
  1,  cdotamatch_metadata__team__player_kill__number_ranges,
  (ProtobufCMessageInit) cdotamatch_metadata__team__player_kill__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotamatch_metadata__team__item_purchase__field_descriptors[2] =
{
  {
    "item_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__ItemPurchase, has_item_id),
    offsetof(CDOTAMatchMetadata__Team__ItemPurchase, item_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "purchase_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CDOTAMatchMetadata__Team__ItemPurchase, has_purchase_time),
    offsetof(CDOTAMatchMetadata__Team__ItemPurchase, purchase_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotamatch_metadata__team__item_purchase__field_indices_by_name[] = {
  0,   /* field[0] = item_id */
  1,   /* field[1] = purchase_time */
};
static const ProtobufCIntRange cdotamatch_metadata__team__item_purchase__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cdotamatch_metadata__team__item_purchase__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTAMatchMetadata.Team.ItemPurchase",
  "ItemPurchase",
  "CDOTAMatchMetadata__Team__ItemPurchase",
  "",
  sizeof(CDOTAMatchMetadata__Team__ItemPurchase),
  2,
  cdotamatch_metadata__team__item_purchase__field_descriptors,
  cdotamatch_metadata__team__item_purchase__field_indices_by_name,
  1,  cdotamatch_metadata__team__item_purchase__number_ranges,
  (ProtobufCMessageInit) cdotamatch_metadata__team__item_purchase__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotamatch_metadata__team__player__field_descriptors[23] =
{
  {
    "account_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_account_id),
    offsetof(CDOTAMatchMetadata__Team__Player, account_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ability_upgrades",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, n_ability_upgrades),
    offsetof(CDOTAMatchMetadata__Team__Player, ability_upgrades),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_slot",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_player_slot),
    offsetof(CDOTAMatchMetadata__Team__Player, player_slot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "equipped_econ_items",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTAMatchMetadata__Team__Player, n_equipped_econ_items),
    offsetof(CDOTAMatchMetadata__Team__Player, equipped_econ_items),
    &csoecon_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kills",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTAMatchMetadata__Team__Player, n_kills),
    offsetof(CDOTAMatchMetadata__Team__Player, kills),
    &cdotamatch_metadata__team__player_kill__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTAMatchMetadata__Team__Player, n_items),
    offsetof(CDOTAMatchMetadata__Team__Player, items),
    &cdotamatch_metadata__team__item_purchase__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avg_kills_x16",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_avg_kills_x16),
    offsetof(CDOTAMatchMetadata__Team__Player, avg_kills_x16),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avg_deaths_x16",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_avg_deaths_x16),
    offsetof(CDOTAMatchMetadata__Team__Player, avg_deaths_x16),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avg_assists_x16",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_avg_assists_x16),
    offsetof(CDOTAMatchMetadata__Team__Player, avg_assists_x16),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avg_gpm_x16",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_avg_gpm_x16),
    offsetof(CDOTAMatchMetadata__Team__Player, avg_gpm_x16),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avg_xpm_x16",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_avg_xpm_x16),
    offsetof(CDOTAMatchMetadata__Team__Player, avg_xpm_x16),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "best_kills_x16",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_best_kills_x16),
    offsetof(CDOTAMatchMetadata__Team__Player, best_kills_x16),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "best_assists_x16",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_best_assists_x16),
    offsetof(CDOTAMatchMetadata__Team__Player, best_assists_x16),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "best_gpm_x16",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_best_gpm_x16),
    offsetof(CDOTAMatchMetadata__Team__Player, best_gpm_x16),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "best_xpm_x16",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_best_xpm_x16),
    offsetof(CDOTAMatchMetadata__Team__Player, best_xpm_x16),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "win_streak",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_win_streak),
    offsetof(CDOTAMatchMetadata__Team__Player, win_streak),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "best_win_streak",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, has_best_win_streak),
    offsetof(CDOTAMatchMetadata__Team__Player, best_win_streak),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fight_score",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDOTAMatchMetadata__Team__Player, has_fight_score),
    offsetof(CDOTAMatchMetadata__Team__Player, fight_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "farm_score",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDOTAMatchMetadata__Team__Player, has_farm_score),
    offsetof(CDOTAMatchMetadata__Team__Player, farm_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "support_score",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDOTAMatchMetadata__Team__Player, has_support_score),
    offsetof(CDOTAMatchMetadata__Team__Player, support_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "push_score",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDOTAMatchMetadata__Team__Player, has_push_score),
    offsetof(CDOTAMatchMetadata__Team__Player, push_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level_up_times",
    22,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team__Player, n_level_up_times),
    offsetof(CDOTAMatchMetadata__Team__Player, level_up_times),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "graph_net_worth",
    23,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDOTAMatchMetadata__Team__Player, n_graph_net_worth),
    offsetof(CDOTAMatchMetadata__Team__Player, graph_net_worth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotamatch_metadata__team__player__field_indices_by_name[] = {
  1,   /* field[1] = ability_upgrades */
  0,   /* field[0] = account_id */
  8,   /* field[8] = avg_assists_x16 */
  7,   /* field[7] = avg_deaths_x16 */
  9,   /* field[9] = avg_gpm_x16 */
  6,   /* field[6] = avg_kills_x16 */
  10,   /* field[10] = avg_xpm_x16 */
  12,   /* field[12] = best_assists_x16 */
  13,   /* field[13] = best_gpm_x16 */
  11,   /* field[11] = best_kills_x16 */
  16,   /* field[16] = best_win_streak */
  14,   /* field[14] = best_xpm_x16 */
  3,   /* field[3] = equipped_econ_items */
  18,   /* field[18] = farm_score */
  17,   /* field[17] = fight_score */
  22,   /* field[22] = graph_net_worth */
  5,   /* field[5] = items */
  4,   /* field[4] = kills */
  21,   /* field[21] = level_up_times */
  2,   /* field[2] = player_slot */
  20,   /* field[20] = push_score */
  19,   /* field[19] = support_score */
  15,   /* field[15] = win_streak */
};
static const ProtobufCIntRange cdotamatch_metadata__team__player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 23 }
};
const ProtobufCMessageDescriptor cdotamatch_metadata__team__player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTAMatchMetadata.Team.Player",
  "Player",
  "CDOTAMatchMetadata__Team__Player",
  "",
  sizeof(CDOTAMatchMetadata__Team__Player),
  23,
  cdotamatch_metadata__team__player__field_descriptors,
  cdotamatch_metadata__team__player__field_indices_by_name,
  1,  cdotamatch_metadata__team__player__number_ranges,
  (ProtobufCMessageInit) cdotamatch_metadata__team__player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotamatch_metadata__team__field_descriptors[10] =
{
  {
    "dota_team",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team, has_dota_team),
    offsetof(CDOTAMatchMetadata__Team, dota_team),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "players",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTAMatchMetadata__Team, n_players),
    offsetof(CDOTAMatchMetadata__Team, players),
    &cdotamatch_metadata__team__player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "graph_experience",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDOTAMatchMetadata__Team, n_graph_experience),
    offsetof(CDOTAMatchMetadata__Team, graph_experience),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "graph_gold_earned",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDOTAMatchMetadata__Team, n_graph_gold_earned),
    offsetof(CDOTAMatchMetadata__Team, graph_gold_earned),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "graph_net_worth",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDOTAMatchMetadata__Team, n_graph_net_worth),
    offsetof(CDOTAMatchMetadata__Team, graph_net_worth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cm_first_pick",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CDOTAMatchMetadata__Team, has_cm_first_pick),
    offsetof(CDOTAMatchMetadata__Team, cm_first_pick),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cm_captain_player_id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team, has_cm_captain_player_id),
    offsetof(CDOTAMatchMetadata__Team, cm_captain_player_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cm_bans",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team, n_cm_bans),
    offsetof(CDOTAMatchMetadata__Team, cm_bans),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cm_picks",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team, n_cm_picks),
    offsetof(CDOTAMatchMetadata__Team, cm_picks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cm_penalty",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchMetadata__Team, has_cm_penalty),
    offsetof(CDOTAMatchMetadata__Team, cm_penalty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotamatch_metadata__team__field_indices_by_name[] = {
  7,   /* field[7] = cm_bans */
  6,   /* field[6] = cm_captain_player_id */
  5,   /* field[5] = cm_first_pick */
  9,   /* field[9] = cm_penalty */
  8,   /* field[8] = cm_picks */
  0,   /* field[0] = dota_team */
  2,   /* field[2] = graph_experience */
  3,   /* field[3] = graph_gold_earned */
  4,   /* field[4] = graph_net_worth */
  1,   /* field[1] = players */
};
static const ProtobufCIntRange cdotamatch_metadata__team__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor cdotamatch_metadata__team__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTAMatchMetadata.Team",
  "Team",
  "CDOTAMatchMetadata__Team",
  "",
  sizeof(CDOTAMatchMetadata__Team),
  10,
  cdotamatch_metadata__team__field_descriptors,
  cdotamatch_metadata__team__field_indices_by_name,
  1,  cdotamatch_metadata__team__number_ranges,
  (ProtobufCMessageInit) cdotamatch_metadata__team__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotamatch_metadata__field_descriptors[2] =
{
  {
    "teams",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTAMatchMetadata, n_teams),
    offsetof(CDOTAMatchMetadata, teams),
    &cdotamatch_metadata__team__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item_rewards",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTAMatchMetadata, n_item_rewards),
    offsetof(CDOTAMatchMetadata, item_rewards),
    &clobby_timed_reward_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotamatch_metadata__field_indices_by_name[] = {
  1,   /* field[1] = item_rewards */
  0,   /* field[0] = teams */
};
static const ProtobufCIntRange cdotamatch_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cdotamatch_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTAMatchMetadata",
  "CDOTAMatchMetadata",
  "CDOTAMatchMetadata",
  "",
  sizeof(CDOTAMatchMetadata),
  2,
  cdotamatch_metadata__field_descriptors,
  cdotamatch_metadata__field_indices_by_name,
  1,  cdotamatch_metadata__number_ranges,
  (ProtobufCMessageInit) cdotamatch_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotamatch_private_metadata__team__player__field_descriptors[3] =
{
  {
    "account_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchPrivateMetadata__Team__Player, has_account_id),
    offsetof(CDOTAMatchPrivateMetadata__Team__Player, account_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_slot",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchPrivateMetadata__Team__Player, has_player_slot),
    offsetof(CDOTAMatchPrivateMetadata__Team__Player, player_slot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_stream",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CDOTAMatchPrivateMetadata__Team__Player, has_position_stream),
    offsetof(CDOTAMatchPrivateMetadata__Team__Player, position_stream),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotamatch_private_metadata__team__player__field_indices_by_name[] = {
  0,   /* field[0] = account_id */
  1,   /* field[1] = player_slot */
  2,   /* field[2] = position_stream */
};
static const ProtobufCIntRange cdotamatch_private_metadata__team__player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cdotamatch_private_metadata__team__player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTAMatchPrivateMetadata.Team.Player",
  "Player",
  "CDOTAMatchPrivateMetadata__Team__Player",
  "",
  sizeof(CDOTAMatchPrivateMetadata__Team__Player),
  3,
  cdotamatch_private_metadata__team__player__field_descriptors,
  cdotamatch_private_metadata__team__player__field_indices_by_name,
  1,  cdotamatch_private_metadata__team__player__number_ranges,
  (ProtobufCMessageInit) cdotamatch_private_metadata__team__player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotamatch_private_metadata__team__field_descriptors[2] =
{
  {
    "dota_team",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAMatchPrivateMetadata__Team, has_dota_team),
    offsetof(CDOTAMatchPrivateMetadata__Team, dota_team),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "players",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTAMatchPrivateMetadata__Team, n_players),
    offsetof(CDOTAMatchPrivateMetadata__Team, players),
    &cdotamatch_private_metadata__team__player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotamatch_private_metadata__team__field_indices_by_name[] = {
  0,   /* field[0] = dota_team */
  1,   /* field[1] = players */
};
static const ProtobufCIntRange cdotamatch_private_metadata__team__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cdotamatch_private_metadata__team__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTAMatchPrivateMetadata.Team",
  "Team",
  "CDOTAMatchPrivateMetadata__Team",
  "",
  sizeof(CDOTAMatchPrivateMetadata__Team),
  2,
  cdotamatch_private_metadata__team__field_descriptors,
  cdotamatch_private_metadata__team__field_indices_by_name,
  1,  cdotamatch_private_metadata__team__number_ranges,
  (ProtobufCMessageInit) cdotamatch_private_metadata__team__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotamatch_private_metadata__field_descriptors[1] =
{
  {
    "teams",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTAMatchPrivateMetadata, n_teams),
    offsetof(CDOTAMatchPrivateMetadata, teams),
    &cdotamatch_private_metadata__team__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotamatch_private_metadata__field_indices_by_name[] = {
  0,   /* field[0] = teams */
};
static const ProtobufCIntRange cdotamatch_private_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cdotamatch_private_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTAMatchPrivateMetadata",
  "CDOTAMatchPrivateMetadata",
  "CDOTAMatchPrivateMetadata",
  "",
  sizeof(CDOTAMatchPrivateMetadata),
  1,
  cdotamatch_private_metadata__field_descriptors,
  cdotamatch_private_metadata__field_indices_by_name,
  1,  cdotamatch_private_metadata__number_ranges,
  (ProtobufCMessageInit) cdotamatch_private_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
