/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dota_shared_enums.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dota_shared_enums.pb-c.h"
void   cdotaclient_hardware_specs__init
                     (CDOTAClientHardwareSpecs         *message)
{
  static CDOTAClientHardwareSpecs init_value = CDOTACLIENT_HARDWARE_SPECS__INIT;
  *message = init_value;
}
size_t cdotaclient_hardware_specs__get_packed_size
                     (const CDOTAClientHardwareSpecs *message)
{
  assert(message->base.descriptor == &cdotaclient_hardware_specs__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdotaclient_hardware_specs__pack
                     (const CDOTAClientHardwareSpecs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdotaclient_hardware_specs__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdotaclient_hardware_specs__pack_to_buffer
                     (const CDOTAClientHardwareSpecs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdotaclient_hardware_specs__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDOTAClientHardwareSpecs *
       cdotaclient_hardware_specs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDOTAClientHardwareSpecs *)
     protobuf_c_message_unpack (&cdotaclient_hardware_specs__descriptor,
                                allocator, len, data);
}
void   cdotaclient_hardware_specs__free_unpacked
                     (CDOTAClientHardwareSpecs *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdotaclient_hardware_specs__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cdotasave_game__player__init
                     (CDOTASaveGame__Player         *message)
{
  static CDOTASaveGame__Player init_value = CDOTASAVE_GAME__PLAYER__INIT;
  *message = init_value;
}
void   cdotasave_game__save_instance__player_positions__init
                     (CDOTASaveGame__SaveInstance__PlayerPositions         *message)
{
  static CDOTASaveGame__SaveInstance__PlayerPositions init_value = CDOTASAVE_GAME__SAVE_INSTANCE__PLAYER_POSITIONS__INIT;
  *message = init_value;
}
void   cdotasave_game__save_instance__init
                     (CDOTASaveGame__SaveInstance         *message)
{
  static CDOTASaveGame__SaveInstance init_value = CDOTASAVE_GAME__SAVE_INSTANCE__INIT;
  *message = init_value;
}
void   cdotasave_game__init
                     (CDOTASaveGame         *message)
{
  static CDOTASaveGame init_value = CDOTASAVE_GAME__INIT;
  *message = init_value;
}
size_t cdotasave_game__get_packed_size
                     (const CDOTASaveGame *message)
{
  assert(message->base.descriptor == &cdotasave_game__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cdotasave_game__pack
                     (const CDOTASaveGame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cdotasave_game__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cdotasave_game__pack_to_buffer
                     (const CDOTASaveGame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cdotasave_game__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CDOTASaveGame *
       cdotasave_game__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CDOTASaveGame *)
     protobuf_c_message_unpack (&cdotasave_game__descriptor,
                                allocator, len, data);
}
void   cdotasave_game__free_unpacked
                     (CDOTASaveGame *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cdotasave_game__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cdotaclient_hardware_specs__field_descriptors[6] =
{
  {
    "logical_processors",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTAClientHardwareSpecs, has_logical_processors),
    offsetof(CDOTAClientHardwareSpecs, logical_processors),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_cycles_per_second",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(CDOTAClientHardwareSpecs, has_cpu_cycles_per_second),
    offsetof(CDOTAClientHardwareSpecs, cpu_cycles_per_second),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_physical_memory",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(CDOTAClientHardwareSpecs, has_total_physical_memory),
    offsetof(CDOTAClientHardwareSpecs, total_physical_memory),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_64_bit_os",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CDOTAClientHardwareSpecs, has_is_64_bit_os),
    offsetof(CDOTAClientHardwareSpecs, is_64_bit_os),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "upload_measurement",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CDOTAClientHardwareSpecs, has_upload_measurement),
    offsetof(CDOTAClientHardwareSpecs, upload_measurement),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prefer_not_host",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CDOTAClientHardwareSpecs, has_prefer_not_host),
    offsetof(CDOTAClientHardwareSpecs, prefer_not_host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotaclient_hardware_specs__field_indices_by_name[] = {
  1,   /* field[1] = cpu_cycles_per_second */
  3,   /* field[3] = is_64_bit_os */
  0,   /* field[0] = logical_processors */
  5,   /* field[5] = prefer_not_host */
  2,   /* field[2] = total_physical_memory */
  4,   /* field[4] = upload_measurement */
};
static const ProtobufCIntRange cdotaclient_hardware_specs__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor cdotaclient_hardware_specs__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTAClientHardwareSpecs",
  "CDOTAClientHardwareSpecs",
  "CDOTAClientHardwareSpecs",
  "",
  sizeof(CDOTAClientHardwareSpecs),
  6,
  cdotaclient_hardware_specs__field_descriptors,
  cdotaclient_hardware_specs__field_indices_by_name,
  1,  cdotaclient_hardware_specs__number_ranges,
  (ProtobufCMessageInit) cdotaclient_hardware_specs__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const DOTAGCTEAM cdotasave_game__player__team__default_value = DOTA__GC__TEAM__DOTA_GC_TEAM_GOOD_GUYS;
static const ProtobufCFieldDescriptor cdotasave_game__player__field_descriptors[3] =
{
  {
    "team",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CDOTASaveGame__Player, has_team),
    offsetof(CDOTASaveGame__Player, team),
    &dota__gc__team__descriptor,
    &cdotasave_game__player__team__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDOTASaveGame__Player, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hero",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CDOTASaveGame__Player, hero),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotasave_game__player__field_indices_by_name[] = {
  2,   /* field[2] = hero */
  1,   /* field[1] = name */
  0,   /* field[0] = team */
};
static const ProtobufCIntRange cdotasave_game__player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cdotasave_game__player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTASaveGame.Player",
  "Player",
  "CDOTASaveGame__Player",
  "",
  sizeof(CDOTASaveGame__Player),
  3,
  cdotasave_game__player__field_descriptors,
  cdotasave_game__player__field_indices_by_name,
  1,  cdotasave_game__player__number_ranges,
  (ProtobufCMessageInit) cdotasave_game__player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotasave_game__save_instance__player_positions__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDOTASaveGame__SaveInstance__PlayerPositions, has_x),
    offsetof(CDOTASaveGame__SaveInstance__PlayerPositions, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CDOTASaveGame__SaveInstance__PlayerPositions, has_y),
    offsetof(CDOTASaveGame__SaveInstance__PlayerPositions, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotasave_game__save_instance__player_positions__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange cdotasave_game__save_instance__player_positions__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cdotasave_game__save_instance__player_positions__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTASaveGame.SaveInstance.PlayerPositions",
  "PlayerPositions",
  "CDOTASaveGame__SaveInstance__PlayerPositions",
  "",
  sizeof(CDOTASaveGame__SaveInstance__PlayerPositions),
  2,
  cdotasave_game__save_instance__player_positions__field_descriptors,
  cdotasave_game__save_instance__player_positions__field_indices_by_name,
  1,  cdotasave_game__save_instance__player_positions__number_ranges,
  (ProtobufCMessageInit) cdotasave_game__save_instance__player_positions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotasave_game__save_instance__field_descriptors[6] =
{
  {
    "game_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTASaveGame__SaveInstance, has_game_time),
    offsetof(CDOTASaveGame__SaveInstance, game_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "team1_score",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTASaveGame__SaveInstance, has_team1_score),
    offsetof(CDOTASaveGame__SaveInstance, team1_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "team2_score",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTASaveGame__SaveInstance, has_team2_score),
    offsetof(CDOTASaveGame__SaveInstance, team2_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_positions",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTASaveGame__SaveInstance, n_player_positions),
    offsetof(CDOTASaveGame__SaveInstance, player_positions),
    &cdotasave_game__save_instance__player_positions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "save_id",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTASaveGame__SaveInstance, has_save_id),
    offsetof(CDOTASaveGame__SaveInstance, save_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "save_time",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTASaveGame__SaveInstance, has_save_time),
    offsetof(CDOTASaveGame__SaveInstance, save_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotasave_game__save_instance__field_indices_by_name[] = {
  0,   /* field[0] = game_time */
  3,   /* field[3] = player_positions */
  4,   /* field[4] = save_id */
  5,   /* field[5] = save_time */
  1,   /* field[1] = team1_score */
  2,   /* field[2] = team2_score */
};
static const ProtobufCIntRange cdotasave_game__save_instance__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor cdotasave_game__save_instance__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTASaveGame.SaveInstance",
  "SaveInstance",
  "CDOTASaveGame__SaveInstance",
  "",
  sizeof(CDOTASaveGame__SaveInstance),
  6,
  cdotasave_game__save_instance__field_descriptors,
  cdotasave_game__save_instance__field_indices_by_name,
  1,  cdotasave_game__save_instance__number_ranges,
  (ProtobufCMessageInit) cdotasave_game__save_instance__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cdotasave_game__field_descriptors[4] =
{
  {
    "save_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CDOTASaveGame, has_save_time),
    offsetof(CDOTASaveGame, save_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "players",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTASaveGame, n_players),
    offsetof(CDOTASaveGame, players),
    &cdotasave_game__player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "save_instances",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CDOTASaveGame, n_save_instances),
    offsetof(CDOTASaveGame, save_instances),
    &cdotasave_game__save_instance__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CDOTASaveGame, has_match_id),
    offsetof(CDOTASaveGame, match_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cdotasave_game__field_indices_by_name[] = {
  3,   /* field[3] = match_id */
  1,   /* field[1] = players */
  2,   /* field[2] = save_instances */
  0,   /* field[0] = save_time */
};
static const ProtobufCIntRange cdotasave_game__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cdotasave_game__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CDOTASaveGame",
  "CDOTASaveGame",
  "CDOTASaveGame",
  "",
  sizeof(CDOTASaveGame),
  4,
  cdotasave_game__field_descriptors,
  cdotasave_game__field_indices_by_name,
  1,  cdotasave_game__number_ranges,
  (ProtobufCMessageInit) cdotasave_game__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dota__game_mode__enum_values_by_number[23] =
{
  { "DOTA_GAMEMODE_NONE", "DOTA__GAME_MODE__DOTA_GAMEMODE_NONE", 0 },
  { "DOTA_GAMEMODE_AP", "DOTA__GAME_MODE__DOTA_GAMEMODE_AP", 1 },
  { "DOTA_GAMEMODE_CM", "DOTA__GAME_MODE__DOTA_GAMEMODE_CM", 2 },
  { "DOTA_GAMEMODE_RD", "DOTA__GAME_MODE__DOTA_GAMEMODE_RD", 3 },
  { "DOTA_GAMEMODE_SD", "DOTA__GAME_MODE__DOTA_GAMEMODE_SD", 4 },
  { "DOTA_GAMEMODE_AR", "DOTA__GAME_MODE__DOTA_GAMEMODE_AR", 5 },
  { "DOTA_GAMEMODE_INTRO", "DOTA__GAME_MODE__DOTA_GAMEMODE_INTRO", 6 },
  { "DOTA_GAMEMODE_HW", "DOTA__GAME_MODE__DOTA_GAMEMODE_HW", 7 },
  { "DOTA_GAMEMODE_REVERSE_CM", "DOTA__GAME_MODE__DOTA_GAMEMODE_REVERSE_CM", 8 },
  { "DOTA_GAMEMODE_XMAS", "DOTA__GAME_MODE__DOTA_GAMEMODE_XMAS", 9 },
  { "DOTA_GAMEMODE_TUTORIAL", "DOTA__GAME_MODE__DOTA_GAMEMODE_TUTORIAL", 10 },
  { "DOTA_GAMEMODE_MO", "DOTA__GAME_MODE__DOTA_GAMEMODE_MO", 11 },
  { "DOTA_GAMEMODE_LP", "DOTA__GAME_MODE__DOTA_GAMEMODE_LP", 12 },
  { "DOTA_GAMEMODE_POOL1", "DOTA__GAME_MODE__DOTA_GAMEMODE_POOL1", 13 },
  { "DOTA_GAMEMODE_FH", "DOTA__GAME_MODE__DOTA_GAMEMODE_FH", 14 },
  { "DOTA_GAMEMODE_CUSTOM", "DOTA__GAME_MODE__DOTA_GAMEMODE_CUSTOM", 15 },
  { "DOTA_GAMEMODE_CD", "DOTA__GAME_MODE__DOTA_GAMEMODE_CD", 16 },
  { "DOTA_GAMEMODE_BD", "DOTA__GAME_MODE__DOTA_GAMEMODE_BD", 17 },
  { "DOTA_GAMEMODE_ABILITY_DRAFT", "DOTA__GAME_MODE__DOTA_GAMEMODE_ABILITY_DRAFT", 18 },
  { "DOTA_GAMEMODE_EVENT", "DOTA__GAME_MODE__DOTA_GAMEMODE_EVENT", 19 },
  { "DOTA_GAMEMODE_ARDM", "DOTA__GAME_MODE__DOTA_GAMEMODE_ARDM", 20 },
  { "DOTA_GAMEMODE_1V1MID", "DOTA__GAME_MODE__DOTA_GAMEMODE_1V1MID", 21 },
  { "DOTA_GAMEMODE_ALL_DRAFT", "DOTA__GAME_MODE__DOTA_GAMEMODE_ALL_DRAFT", 22 },
};
static const ProtobufCIntRange dota__game_mode__value_ranges[] = {
{0, 0},{0, 23}
};
static const ProtobufCEnumValueIndex dota__game_mode__enum_values_by_name[23] =
{
  { "DOTA_GAMEMODE_1V1MID", 21 },
  { "DOTA_GAMEMODE_ABILITY_DRAFT", 18 },
  { "DOTA_GAMEMODE_ALL_DRAFT", 22 },
  { "DOTA_GAMEMODE_AP", 1 },
  { "DOTA_GAMEMODE_AR", 5 },
  { "DOTA_GAMEMODE_ARDM", 20 },
  { "DOTA_GAMEMODE_BD", 17 },
  { "DOTA_GAMEMODE_CD", 16 },
  { "DOTA_GAMEMODE_CM", 2 },
  { "DOTA_GAMEMODE_CUSTOM", 15 },
  { "DOTA_GAMEMODE_EVENT", 19 },
  { "DOTA_GAMEMODE_FH", 14 },
  { "DOTA_GAMEMODE_HW", 7 },
  { "DOTA_GAMEMODE_INTRO", 6 },
  { "DOTA_GAMEMODE_LP", 12 },
  { "DOTA_GAMEMODE_MO", 11 },
  { "DOTA_GAMEMODE_NONE", 0 },
  { "DOTA_GAMEMODE_POOL1", 13 },
  { "DOTA_GAMEMODE_RD", 3 },
  { "DOTA_GAMEMODE_REVERSE_CM", 8 },
  { "DOTA_GAMEMODE_SD", 4 },
  { "DOTA_GAMEMODE_TUTORIAL", 10 },
  { "DOTA_GAMEMODE_XMAS", 9 },
};
const ProtobufCEnumDescriptor dota__game_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTA_GameMode",
  "DOTA_GameMode",
  "DOTAGameMode",
  "",
  23,
  dota__game_mode__enum_values_by_number,
  23,
  dota__game_mode__enum_values_by_name,
  1,
  dota__game_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dota__game_state__enum_values_by_number[11] =
{
  { "DOTA_GAMERULES_STATE_INIT", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_INIT", 0 },
  { "DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD", 1 },
  { "DOTA_GAMERULES_STATE_HERO_SELECTION", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_HERO_SELECTION", 2 },
  { "DOTA_GAMERULES_STATE_STRATEGY_TIME", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_STRATEGY_TIME", 3 },
  { "DOTA_GAMERULES_STATE_PRE_GAME", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_PRE_GAME", 4 },
  { "DOTA_GAMERULES_STATE_GAME_IN_PROGRESS", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_GAME_IN_PROGRESS", 5 },
  { "DOTA_GAMERULES_STATE_POST_GAME", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_POST_GAME", 6 },
  { "DOTA_GAMERULES_STATE_DISCONNECT", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_DISCONNECT", 7 },
  { "DOTA_GAMERULES_STATE_TEAM_SHOWCASE", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_TEAM_SHOWCASE", 8 },
  { "DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP", 9 },
  { "DOTA_GAMERULES_STATE_LAST", "DOTA__GAME_STATE__DOTA_GAMERULES_STATE_LAST", 10 },
};
static const ProtobufCIntRange dota__game_state__value_ranges[] = {
{0, 0},{0, 11}
};
static const ProtobufCEnumValueIndex dota__game_state__enum_values_by_name[11] =
{
  { "DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP", 9 },
  { "DOTA_GAMERULES_STATE_DISCONNECT", 7 },
  { "DOTA_GAMERULES_STATE_GAME_IN_PROGRESS", 5 },
  { "DOTA_GAMERULES_STATE_HERO_SELECTION", 2 },
  { "DOTA_GAMERULES_STATE_INIT", 0 },
  { "DOTA_GAMERULES_STATE_LAST", 10 },
  { "DOTA_GAMERULES_STATE_POST_GAME", 6 },
  { "DOTA_GAMERULES_STATE_PRE_GAME", 4 },
  { "DOTA_GAMERULES_STATE_STRATEGY_TIME", 3 },
  { "DOTA_GAMERULES_STATE_TEAM_SHOWCASE", 8 },
  { "DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD", 1 },
};
const ProtobufCEnumDescriptor dota__game_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTA_GameState",
  "DOTA_GameState",
  "DOTAGameState",
  "",
  11,
  dota__game_state__enum_values_by_number,
  11,
  dota__game_state__enum_values_by_name,
  1,
  dota__game_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dota__gc__team__enum_values_by_number[6] =
{
  { "DOTA_GC_TEAM_GOOD_GUYS", "DOTA__GC__TEAM__DOTA_GC_TEAM_GOOD_GUYS", 0 },
  { "DOTA_GC_TEAM_BAD_GUYS", "DOTA__GC__TEAM__DOTA_GC_TEAM_BAD_GUYS", 1 },
  { "DOTA_GC_TEAM_BROADCASTER", "DOTA__GC__TEAM__DOTA_GC_TEAM_BROADCASTER", 2 },
  { "DOTA_GC_TEAM_SPECTATOR", "DOTA__GC__TEAM__DOTA_GC_TEAM_SPECTATOR", 3 },
  { "DOTA_GC_TEAM_PLAYER_POOL", "DOTA__GC__TEAM__DOTA_GC_TEAM_PLAYER_POOL", 4 },
  { "DOTA_GC_TEAM_NOTEAM", "DOTA__GC__TEAM__DOTA_GC_TEAM_NOTEAM", 5 },
};
static const ProtobufCIntRange dota__gc__team__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex dota__gc__team__enum_values_by_name[6] =
{
  { "DOTA_GC_TEAM_BAD_GUYS", 1 },
  { "DOTA_GC_TEAM_BROADCASTER", 2 },
  { "DOTA_GC_TEAM_GOOD_GUYS", 0 },
  { "DOTA_GC_TEAM_NOTEAM", 5 },
  { "DOTA_GC_TEAM_PLAYER_POOL", 4 },
  { "DOTA_GC_TEAM_SPECTATOR", 3 },
};
const ProtobufCEnumDescriptor dota__gc__team__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTA_GC_TEAM",
  "DOTA_GC_TEAM",
  "DOTAGCTEAM",
  "",
  6,
  dota__gc__team__enum_values_by_number,
  6,
  dota__gc__team__enum_values_by_name,
  1,
  dota__gc__team__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eevent__enum_values_by_number[15] =
{
  { "EVENT_ID_NONE", "EEVENT__EVENT_ID_NONE", 0 },
  { "EVENT_ID_DIRETIDE", "EEVENT__EVENT_ID_DIRETIDE", 1 },
  { "EVENT_ID_SPRING_FESTIVAL", "EEVENT__EVENT_ID_SPRING_FESTIVAL", 2 },
  { "EVENT_ID_FROSTIVUS_2013", "EEVENT__EVENT_ID_FROSTIVUS_2013", 3 },
  { "EVENT_ID_COMPENDIUM_2014", "EEVENT__EVENT_ID_COMPENDIUM_2014", 4 },
  { "EVENT_ID_NEXON_PC_BANG", "EEVENT__EVENT_ID_NEXON_PC_BANG", 5 },
  { "EVENT_ID_PWRD_DAC_2015", "EEVENT__EVENT_ID_PWRD_DAC_2015", 6 },
  { "EVENT_ID_NEW_BLOOM_2015", "EEVENT__EVENT_ID_NEW_BLOOM_2015", 7 },
  { "EVENT_ID_INTERNATIONAL_2015", "EEVENT__EVENT_ID_INTERNATIONAL_2015", 8 },
  { "EVENT_ID_FALL_MAJOR_2015", "EEVENT__EVENT_ID_FALL_MAJOR_2015", 9 },
  { "EVENT_ID_ORACLE_PA", "EEVENT__EVENT_ID_ORACLE_PA", 10 },
  { "EVENT_ID_NEW_BLOOM_2015_PREBEAST", "EEVENT__EVENT_ID_NEW_BLOOM_2015_PREBEAST", 11 },
  { "EVENT_ID_FROSTIVUS", "EEVENT__EVENT_ID_FROSTIVUS", 12 },
  { "EVENT_ID_WINTER_MAJOR_2016", "EEVENT__EVENT_ID_WINTER_MAJOR_2016", 13 },
  { "EVENT_ID_INTERNATIONAL_2016", "EEVENT__EVENT_ID_INTERNATIONAL_2016", 14 },
};
static const ProtobufCIntRange eevent__value_ranges[] = {
{0, 0},{0, 15}
};
static const ProtobufCEnumValueIndex eevent__enum_values_by_name[15] =
{
  { "EVENT_ID_COMPENDIUM_2014", 4 },
  { "EVENT_ID_DIRETIDE", 1 },
  { "EVENT_ID_FALL_MAJOR_2015", 9 },
  { "EVENT_ID_FROSTIVUS", 12 },
  { "EVENT_ID_FROSTIVUS_2013", 3 },
  { "EVENT_ID_INTERNATIONAL_2015", 8 },
  { "EVENT_ID_INTERNATIONAL_2016", 14 },
  { "EVENT_ID_NEW_BLOOM_2015", 7 },
  { "EVENT_ID_NEW_BLOOM_2015_PREBEAST", 11 },
  { "EVENT_ID_NEXON_PC_BANG", 5 },
  { "EVENT_ID_NONE", 0 },
  { "EVENT_ID_ORACLE_PA", 10 },
  { "EVENT_ID_PWRD_DAC_2015", 6 },
  { "EVENT_ID_SPRING_FESTIVAL", 2 },
  { "EVENT_ID_WINTER_MAJOR_2016", 13 },
};
const ProtobufCEnumDescriptor eevent__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EEvent",
  "EEvent",
  "EEvent",
  "",
  15,
  eevent__enum_values_by_number,
  15,
  eevent__enum_values_by_name,
  1,
  eevent__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dotaleaver_status_t__enum_values_by_number[9] =
{
  { "DOTA_LEAVER_NONE", "DOTALEAVER_STATUS_T__DOTA_LEAVER_NONE", 0 },
  { "DOTA_LEAVER_DISCONNECTED", "DOTALEAVER_STATUS_T__DOTA_LEAVER_DISCONNECTED", 1 },
  { "DOTA_LEAVER_DISCONNECTED_TOO_LONG", "DOTALEAVER_STATUS_T__DOTA_LEAVER_DISCONNECTED_TOO_LONG", 2 },
  { "DOTA_LEAVER_ABANDONED", "DOTALEAVER_STATUS_T__DOTA_LEAVER_ABANDONED", 3 },
  { "DOTA_LEAVER_AFK", "DOTALEAVER_STATUS_T__DOTA_LEAVER_AFK", 4 },
  { "DOTA_LEAVER_NEVER_CONNECTED", "DOTALEAVER_STATUS_T__DOTA_LEAVER_NEVER_CONNECTED", 5 },
  { "DOTA_LEAVER_NEVER_CONNECTED_TOO_LONG", "DOTALEAVER_STATUS_T__DOTA_LEAVER_NEVER_CONNECTED_TOO_LONG", 6 },
  { "DOTA_LEAVER_FAILED_TO_READY_UP", "DOTALEAVER_STATUS_T__DOTA_LEAVER_FAILED_TO_READY_UP", 7 },
  { "DOTA_LEAVER_DECLINED", "DOTALEAVER_STATUS_T__DOTA_LEAVER_DECLINED", 8 },
};
static const ProtobufCIntRange dotaleaver_status_t__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex dotaleaver_status_t__enum_values_by_name[9] =
{
  { "DOTA_LEAVER_ABANDONED", 3 },
  { "DOTA_LEAVER_AFK", 4 },
  { "DOTA_LEAVER_DECLINED", 8 },
  { "DOTA_LEAVER_DISCONNECTED", 1 },
  { "DOTA_LEAVER_DISCONNECTED_TOO_LONG", 2 },
  { "DOTA_LEAVER_FAILED_TO_READY_UP", 7 },
  { "DOTA_LEAVER_NEVER_CONNECTED", 5 },
  { "DOTA_LEAVER_NEVER_CONNECTED_TOO_LONG", 6 },
  { "DOTA_LEAVER_NONE", 0 },
};
const ProtobufCEnumDescriptor dotaleaver_status_t__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTALeaverStatus_t",
  "DOTALeaverStatus_t",
  "DOTALeaverStatusT",
  "",
  9,
  dotaleaver_status_t__enum_values_by_number,
  9,
  dotaleaver_status_t__enum_values_by_name,
  1,
  dotaleaver_status_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dotaconnection_state_t__enum_values_by_number[7] =
{
  { "DOTA_CONNECTION_STATE_UNKNOWN", "DOTACONNECTION_STATE_T__DOTA_CONNECTION_STATE_UNKNOWN", 0 },
  { "DOTA_CONNECTION_STATE_NOT_YET_CONNECTED", "DOTACONNECTION_STATE_T__DOTA_CONNECTION_STATE_NOT_YET_CONNECTED", 1 },
  { "DOTA_CONNECTION_STATE_CONNECTED", "DOTACONNECTION_STATE_T__DOTA_CONNECTION_STATE_CONNECTED", 2 },
  { "DOTA_CONNECTION_STATE_DISCONNECTED", "DOTACONNECTION_STATE_T__DOTA_CONNECTION_STATE_DISCONNECTED", 3 },
  { "DOTA_CONNECTION_STATE_ABANDONED", "DOTACONNECTION_STATE_T__DOTA_CONNECTION_STATE_ABANDONED", 4 },
  { "DOTA_CONNECTION_STATE_LOADING", "DOTACONNECTION_STATE_T__DOTA_CONNECTION_STATE_LOADING", 5 },
  { "DOTA_CONNECTION_STATE_FAILED", "DOTACONNECTION_STATE_T__DOTA_CONNECTION_STATE_FAILED", 6 },
};
static const ProtobufCIntRange dotaconnection_state_t__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex dotaconnection_state_t__enum_values_by_name[7] =
{
  { "DOTA_CONNECTION_STATE_ABANDONED", 4 },
  { "DOTA_CONNECTION_STATE_CONNECTED", 2 },
  { "DOTA_CONNECTION_STATE_DISCONNECTED", 3 },
  { "DOTA_CONNECTION_STATE_FAILED", 6 },
  { "DOTA_CONNECTION_STATE_LOADING", 5 },
  { "DOTA_CONNECTION_STATE_NOT_YET_CONNECTED", 1 },
  { "DOTA_CONNECTION_STATE_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor dotaconnection_state_t__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTAConnectionState_t",
  "DOTAConnectionState_t",
  "DOTAConnectionStateT",
  "",
  7,
  dotaconnection_state_t__enum_values_by_number,
  7,
  dotaconnection_state_t__enum_values_by_name,
  1,
  dotaconnection_state_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fantasy__roles__enum_values_by_number[3] =
{
  { "FANTASY_ROLE_UNDEFINED", "FANTASY__ROLES__FANTASY_ROLE_UNDEFINED", 0 },
  { "FANTASY_ROLE_CORE", "FANTASY__ROLES__FANTASY_ROLE_CORE", 1 },
  { "FANTASY_ROLE_SUPPORT", "FANTASY__ROLES__FANTASY_ROLE_SUPPORT", 2 },
};
static const ProtobufCIntRange fantasy__roles__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex fantasy__roles__enum_values_by_name[3] =
{
  { "FANTASY_ROLE_CORE", 1 },
  { "FANTASY_ROLE_SUPPORT", 2 },
  { "FANTASY_ROLE_UNDEFINED", 0 },
};
const ProtobufCEnumDescriptor fantasy__roles__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Fantasy_Roles",
  "Fantasy_Roles",
  "FantasyRoles",
  "",
  3,
  fantasy__roles__enum_values_by_number,
  3,
  fantasy__roles__enum_values_by_name,
  1,
  fantasy__roles__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fantasy__team__slots__enum_values_by_number[5] =
{
  { "FANTASY_SLOT_NONE", "FANTASY__TEAM__SLOTS__FANTASY_SLOT_NONE", 0 },
  { "FANTASY_SLOT_CORE", "FANTASY__TEAM__SLOTS__FANTASY_SLOT_CORE", 1 },
  { "FANTASY_SLOT_SUPPORT", "FANTASY__TEAM__SLOTS__FANTASY_SLOT_SUPPORT", 2 },
  { "FANTASY_SLOT_ANY", "FANTASY__TEAM__SLOTS__FANTASY_SLOT_ANY", 3 },
  { "FANTASY_SLOT_BENCH", "FANTASY__TEAM__SLOTS__FANTASY_SLOT_BENCH", 4 },
};
static const ProtobufCIntRange fantasy__team__slots__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex fantasy__team__slots__enum_values_by_name[5] =
{
  { "FANTASY_SLOT_ANY", 3 },
  { "FANTASY_SLOT_BENCH", 4 },
  { "FANTASY_SLOT_CORE", 1 },
  { "FANTASY_SLOT_NONE", 0 },
  { "FANTASY_SLOT_SUPPORT", 2 },
};
const ProtobufCEnumDescriptor fantasy__team__slots__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Fantasy_Team_Slots",
  "Fantasy_Team_Slots",
  "FantasyTeamSlots",
  "",
  5,
  fantasy__team__slots__enum_values_by_number,
  5,
  fantasy__team__slots__enum_values_by_name,
  1,
  fantasy__team__slots__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fantasy__selection__mode__enum_values_by_number[10] =
{
  { "FANTASY_SELECTION_INVALID", "FANTASY__SELECTION__MODE__FANTASY_SELECTION_INVALID", 0 },
  { "FANTASY_SELECTION_LOCKED", "FANTASY__SELECTION__MODE__FANTASY_SELECTION_LOCKED", 1 },
  { "FANTASY_SELECTION_SHUFFLE", "FANTASY__SELECTION__MODE__FANTASY_SELECTION_SHUFFLE", 2 },
  { "FANTASY_SELECTION_FREE_PICK", "FANTASY__SELECTION__MODE__FANTASY_SELECTION_FREE_PICK", 3 },
  { "FANTASY_SELECTION_ENDED", "FANTASY__SELECTION__MODE__FANTASY_SELECTION_ENDED", 4 },
  { "FANTASY_SELECTION_PRE_SEASON", "FANTASY__SELECTION__MODE__FANTASY_SELECTION_PRE_SEASON", 5 },
  { "FANTASY_SELECTION_PRE_DRAFT", "FANTASY__SELECTION__MODE__FANTASY_SELECTION_PRE_DRAFT", 6 },
  { "FANTASY_SELECTION_DRAFTING", "FANTASY__SELECTION__MODE__FANTASY_SELECTION_DRAFTING", 7 },
  { "FANTASY_SELECTION_REGULAR_SEASON", "FANTASY__SELECTION__MODE__FANTASY_SELECTION_REGULAR_SEASON", 8 },
  { "FANTASY_SELECTION_CARD_BASED", "FANTASY__SELECTION__MODE__FANTASY_SELECTION_CARD_BASED", 9 },
};
static const ProtobufCIntRange fantasy__selection__mode__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex fantasy__selection__mode__enum_values_by_name[10] =
{
  { "FANTASY_SELECTION_CARD_BASED", 9 },
  { "FANTASY_SELECTION_DRAFTING", 7 },
  { "FANTASY_SELECTION_ENDED", 4 },
  { "FANTASY_SELECTION_FREE_PICK", 3 },
  { "FANTASY_SELECTION_INVALID", 0 },
  { "FANTASY_SELECTION_LOCKED", 1 },
  { "FANTASY_SELECTION_PRE_DRAFT", 6 },
  { "FANTASY_SELECTION_PRE_SEASON", 5 },
  { "FANTASY_SELECTION_REGULAR_SEASON", 8 },
  { "FANTASY_SELECTION_SHUFFLE", 2 },
};
const ProtobufCEnumDescriptor fantasy__selection__mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Fantasy_Selection_Mode",
  "Fantasy_Selection_Mode",
  "FantasySelectionMode",
  "",
  10,
  fantasy__selection__mode__enum_values_by_number,
  10,
  fantasy__selection__mode__enum_values_by_name,
  1,
  fantasy__selection__mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dotachat_channel_type_t__enum_values_by_number[20] =
{
  { "DOTAChannelType_Regional", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Regional", 0 },
  { "DOTAChannelType_Custom", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Custom", 1 },
  { "DOTAChannelType_Party", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Party", 2 },
  { "DOTAChannelType_Lobby", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Lobby", 3 },
  { "DOTAChannelType_Team", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Team", 4 },
  { "DOTAChannelType_Guild", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Guild", 5 },
  { "DOTAChannelType_Fantasy", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Fantasy", 6 },
  { "DOTAChannelType_Whisper", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Whisper", 7 },
  { "DOTAChannelType_Console", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Console", 8 },
  { "DOTAChannelType_Tab", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Tab", 9 },
  { "DOTAChannelType_Invalid", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Invalid", 10 },
  { "DOTAChannelType_GameAll", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_GameAll", 11 },
  { "DOTAChannelType_GameAllies", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_GameAllies", 12 },
  { "DOTAChannelType_GameSpectator", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_GameSpectator", 13 },
  { "DOTAChannelType_GameCoaching", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_GameCoaching", 14 },
  { "DOTAChannelType_Cafe", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Cafe", 15 },
  { "DOTAChannelType_CustomGame", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_CustomGame", 16 },
  { "DOTAChannelType_Private", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_Private", 17 },
  { "DOTAChannelType_PostGame", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_PostGame", 18 },
  { "DOTAChannelType_BattleCup", "DOTACHAT_CHANNEL_TYPE_T__DOTAChannelType_BattleCup", 19 },
};
static const ProtobufCIntRange dotachat_channel_type_t__value_ranges[] = {
{0, 0},{0, 20}
};
static const ProtobufCEnumValueIndex dotachat_channel_type_t__enum_values_by_name[20] =
{
  { "DOTAChannelType_BattleCup", 19 },
  { "DOTAChannelType_Cafe", 15 },
  { "DOTAChannelType_Console", 8 },
  { "DOTAChannelType_Custom", 1 },
  { "DOTAChannelType_CustomGame", 16 },
  { "DOTAChannelType_Fantasy", 6 },
  { "DOTAChannelType_GameAll", 11 },
  { "DOTAChannelType_GameAllies", 12 },
  { "DOTAChannelType_GameCoaching", 14 },
  { "DOTAChannelType_GameSpectator", 13 },
  { "DOTAChannelType_Guild", 5 },
  { "DOTAChannelType_Invalid", 10 },
  { "DOTAChannelType_Lobby", 3 },
  { "DOTAChannelType_Party", 2 },
  { "DOTAChannelType_PostGame", 18 },
  { "DOTAChannelType_Private", 17 },
  { "DOTAChannelType_Regional", 0 },
  { "DOTAChannelType_Tab", 9 },
  { "DOTAChannelType_Team", 4 },
  { "DOTAChannelType_Whisper", 7 },
};
const ProtobufCEnumDescriptor dotachat_channel_type_t__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTAChatChannelType_t",
  "DOTAChatChannelType_t",
  "DOTAChatChannelTypeT",
  "",
  20,
  dotachat_channel_type_t__enum_values_by_number,
  20,
  dotachat_channel_type_t__enum_values_by_name,
  1,
  dotachat_channel_type_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eprofile_card_slot_type__enum_values_by_number[6] =
{
  { "k_EProfileCardSlotType_Empty", "EPROFILE_CARD_SLOT_TYPE__k_EProfileCardSlotType_Empty", 0 },
  { "k_EProfileCardSlotType_Stat", "EPROFILE_CARD_SLOT_TYPE__k_EProfileCardSlotType_Stat", 1 },
  { "k_EProfileCardSlotType_Trophy", "EPROFILE_CARD_SLOT_TYPE__k_EProfileCardSlotType_Trophy", 2 },
  { "k_EProfileCardSlotType_Item", "EPROFILE_CARD_SLOT_TYPE__k_EProfileCardSlotType_Item", 3 },
  { "k_EProfileCardSlotType_Hero", "EPROFILE_CARD_SLOT_TYPE__k_EProfileCardSlotType_Hero", 4 },
  { "k_EProfileCardSlotType_Emoticon", "EPROFILE_CARD_SLOT_TYPE__k_EProfileCardSlotType_Emoticon", 5 },
};
static const ProtobufCIntRange eprofile_card_slot_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex eprofile_card_slot_type__enum_values_by_name[6] =
{
  { "k_EProfileCardSlotType_Emoticon", 5 },
  { "k_EProfileCardSlotType_Empty", 0 },
  { "k_EProfileCardSlotType_Hero", 4 },
  { "k_EProfileCardSlotType_Item", 3 },
  { "k_EProfileCardSlotType_Stat", 1 },
  { "k_EProfileCardSlotType_Trophy", 2 },
};
const ProtobufCEnumDescriptor eprofile_card_slot_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EProfileCardSlotType",
  "EProfileCardSlotType",
  "EProfileCardSlotType",
  "",
  6,
  eprofile_card_slot_type__enum_values_by_number,
  6,
  eprofile_card_slot_type__enum_values_by_name,
  1,
  eprofile_card_slot_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ematch_group_server_status__enum_values_by_number[3] =
{
  { "k_EMatchGroupServerStatus_OK", "EMATCH_GROUP_SERVER_STATUS__k_EMatchGroupServerStatus_OK", 0 },
  { "k_EMatchGroupServerStatus_LimitedAvailability", "EMATCH_GROUP_SERVER_STATUS__k_EMatchGroupServerStatus_LimitedAvailability", 1 },
  { "k_EMatchGroupServerStatus_Offline", "EMATCH_GROUP_SERVER_STATUS__k_EMatchGroupServerStatus_Offline", 2 },
};
static const ProtobufCIntRange ematch_group_server_status__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ematch_group_server_status__enum_values_by_name[3] =
{
  { "k_EMatchGroupServerStatus_LimitedAvailability", 1 },
  { "k_EMatchGroupServerStatus_OK", 0 },
  { "k_EMatchGroupServerStatus_Offline", 2 },
};
const ProtobufCEnumDescriptor ematch_group_server_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EMatchGroupServerStatus",
  "EMatchGroupServerStatus",
  "EMatchGroupServerStatus",
  "",
  3,
  ematch_group_server_status__enum_values_by_number,
  3,
  ematch_group_server_status__enum_values_by_name,
  1,
  ematch_group_server_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dota__cm__pick__enum_values_by_number[3] =
{
  { "DOTA_CM_RANDOM", "DOTA__CM__PICK__DOTA_CM_RANDOM", 0 },
  { "DOTA_CM_GOOD_GUYS", "DOTA__CM__PICK__DOTA_CM_GOOD_GUYS", 1 },
  { "DOTA_CM_BAD_GUYS", "DOTA__CM__PICK__DOTA_CM_BAD_GUYS", 2 },
};
static const ProtobufCIntRange dota__cm__pick__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex dota__cm__pick__enum_values_by_name[3] =
{
  { "DOTA_CM_BAD_GUYS", 2 },
  { "DOTA_CM_GOOD_GUYS", 1 },
  { "DOTA_CM_RANDOM", 0 },
};
const ProtobufCEnumDescriptor dota__cm__pick__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTA_CM_PICK",
  "DOTA_CM_PICK",
  "DOTACMPICK",
  "",
  3,
  dota__cm__pick__enum_values_by_number,
  3,
  dota__cm__pick__enum_values_by_name,
  1,
  dota__cm__pick__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dotalow_priority_ban_type__enum_values_by_number[3] =
{
  { "DOTA_LOW_PRIORITY_BAN_ABANDON", "DOTALOW_PRIORITY_BAN_TYPE__DOTA_LOW_PRIORITY_BAN_ABANDON", 0 },
  { "DOTA_LOW_PRIORITY_BAN_REPORTS", "DOTALOW_PRIORITY_BAN_TYPE__DOTA_LOW_PRIORITY_BAN_REPORTS", 1 },
  { "DOTA_LOW_PRIORITY_BAN_SECONDARY_ABANDON", "DOTALOW_PRIORITY_BAN_TYPE__DOTA_LOW_PRIORITY_BAN_SECONDARY_ABANDON", 2 },
};
static const ProtobufCIntRange dotalow_priority_ban_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex dotalow_priority_ban_type__enum_values_by_name[3] =
{
  { "DOTA_LOW_PRIORITY_BAN_ABANDON", 0 },
  { "DOTA_LOW_PRIORITY_BAN_REPORTS", 1 },
  { "DOTA_LOW_PRIORITY_BAN_SECONDARY_ABANDON", 2 },
};
const ProtobufCEnumDescriptor dotalow_priority_ban_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTALowPriorityBanType",
  "DOTALowPriorityBanType",
  "DOTALowPriorityBanType",
  "",
  3,
  dotalow_priority_ban_type__enum_values_by_number,
  3,
  dotalow_priority_ban_type__enum_values_by_name,
  1,
  dotalow_priority_ban_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dotalobby_ready_state__enum_values_by_number[3] =
{
  { "DOTALobbyReadyState_UNDECLARED", "DOTALOBBY_READY_STATE__DOTALobbyReadyState_UNDECLARED", 0 },
  { "DOTALobbyReadyState_ACCEPTED", "DOTALOBBY_READY_STATE__DOTALobbyReadyState_ACCEPTED", 1 },
  { "DOTALobbyReadyState_DECLINED", "DOTALOBBY_READY_STATE__DOTALobbyReadyState_DECLINED", 2 },
};
static const ProtobufCIntRange dotalobby_ready_state__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex dotalobby_ready_state__enum_values_by_name[3] =
{
  { "DOTALobbyReadyState_ACCEPTED", 1 },
  { "DOTALobbyReadyState_DECLINED", 2 },
  { "DOTALobbyReadyState_UNDECLARED", 0 },
};
const ProtobufCEnumDescriptor dotalobby_ready_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTALobbyReadyState",
  "DOTALobbyReadyState",
  "DOTALobbyReadyState",
  "",
  3,
  dotalobby_ready_state__enum_values_by_number,
  3,
  dotalobby_ready_state__enum_values_by_name,
  1,
  dotalobby_ready_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dotagame_version__enum_values_by_number[2] =
{
  { "GAME_VERSION_CURRENT", "DOTAGAME_VERSION__GAME_VERSION_CURRENT", 0 },
  { "GAME_VERSION_STABLE", "DOTAGAME_VERSION__GAME_VERSION_STABLE", 1 },
};
static const ProtobufCIntRange dotagame_version__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex dotagame_version__enum_values_by_name[2] =
{
  { "GAME_VERSION_CURRENT", 0 },
  { "GAME_VERSION_STABLE", 1 },
};
const ProtobufCEnumDescriptor dotagame_version__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTAGameVersion",
  "DOTAGameVersion",
  "DOTAGameVersion",
  "",
  2,
  dotagame_version__enum_values_by_number,
  2,
  dotagame_version__enum_values_by_name,
  1,
  dotagame_version__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dotajoin_lobby_result__enum_values_by_number[12] =
{
  { "DOTA_JOIN_RESULT_SUCCESS", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_SUCCESS", 0 },
  { "DOTA_JOIN_RESULT_ALREADY_IN_GAME", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_ALREADY_IN_GAME", 1 },
  { "DOTA_JOIN_RESULT_INVALID_LOBBY", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_INVALID_LOBBY", 2 },
  { "DOTA_JOIN_RESULT_INCORRECT_PASSWORD", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_INCORRECT_PASSWORD", 3 },
  { "DOTA_JOIN_RESULT_ACCESS_DENIED", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_ACCESS_DENIED", 4 },
  { "DOTA_JOIN_RESULT_GENERIC_ERROR", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_GENERIC_ERROR", 5 },
  { "DOTA_JOIN_RESULT_INCORRECT_VERSION", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_INCORRECT_VERSION", 6 },
  { "DOTA_JOIN_RESULT_IN_TEAM_PARTY", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_IN_TEAM_PARTY", 7 },
  { "DOTA_JOIN_RESULT_NO_LOBBY_FOUND", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_NO_LOBBY_FOUND", 8 },
  { "DOTA_JOIN_RESULT_LOBBY_FULL", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_LOBBY_FULL", 9 },
  { "DOTA_JOIN_RESULT_CUSTOM_GAME_INCORRECT_VERSION", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_CUSTOM_GAME_INCORRECT_VERSION", 10 },
  { "DOTA_JOIN_RESULT_TIMEOUT", "DOTAJOIN_LOBBY_RESULT__DOTA_JOIN_RESULT_TIMEOUT", 11 },
};
static const ProtobufCIntRange dotajoin_lobby_result__value_ranges[] = {
{0, 0},{0, 12}
};
static const ProtobufCEnumValueIndex dotajoin_lobby_result__enum_values_by_name[12] =
{
  { "DOTA_JOIN_RESULT_ACCESS_DENIED", 4 },
  { "DOTA_JOIN_RESULT_ALREADY_IN_GAME", 1 },
  { "DOTA_JOIN_RESULT_CUSTOM_GAME_INCORRECT_VERSION", 10 },
  { "DOTA_JOIN_RESULT_GENERIC_ERROR", 5 },
  { "DOTA_JOIN_RESULT_INCORRECT_PASSWORD", 3 },
  { "DOTA_JOIN_RESULT_INCORRECT_VERSION", 6 },
  { "DOTA_JOIN_RESULT_INVALID_LOBBY", 2 },
  { "DOTA_JOIN_RESULT_IN_TEAM_PARTY", 7 },
  { "DOTA_JOIN_RESULT_LOBBY_FULL", 9 },
  { "DOTA_JOIN_RESULT_NO_LOBBY_FOUND", 8 },
  { "DOTA_JOIN_RESULT_SUCCESS", 0 },
  { "DOTA_JOIN_RESULT_TIMEOUT", 11 },
};
const ProtobufCEnumDescriptor dotajoin_lobby_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTAJoinLobbyResult",
  "DOTAJoinLobbyResult",
  "DOTAJoinLobbyResult",
  "",
  12,
  dotajoin_lobby_result__enum_values_by_number,
  12,
  dotajoin_lobby_result__enum_values_by_name,
  1,
  dotajoin_lobby_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue selection_priority_type__enum_values_by_number[5] =
{
  { "UNDEFINED", "SELECTION_PRIORITY_TYPE__UNDEFINED", 0 },
  { "RADIANT", "SELECTION_PRIORITY_TYPE__RADIANT", 1 },
  { "DIRE", "SELECTION_PRIORITY_TYPE__DIRE", 2 },
  { "FIRST_PICK", "SELECTION_PRIORITY_TYPE__FIRST_PICK", 3 },
  { "SECOND_PICK", "SELECTION_PRIORITY_TYPE__SECOND_PICK", 4 },
};
static const ProtobufCIntRange selection_priority_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex selection_priority_type__enum_values_by_name[5] =
{
  { "DIRE", 2 },
  { "FIRST_PICK", 3 },
  { "RADIANT", 1 },
  { "SECOND_PICK", 4 },
  { "UNDEFINED", 0 },
};
const ProtobufCEnumDescriptor selection_priority_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SelectionPriorityType",
  "SelectionPriorityType",
  "SelectionPriorityType",
  "",
  5,
  selection_priority_type__enum_values_by_number,
  5,
  selection_priority_type__enum_values_by_name,
  1,
  selection_priority_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dotamatch_vote__enum_values_by_number[3] =
{
  { "DOTAMatchVote_INVALID", "DOTAMATCH_VOTE__DOTAMatchVote_INVALID", 0 },
  { "DOTAMatchVote_POSITIVE", "DOTAMATCH_VOTE__DOTAMatchVote_POSITIVE", 1 },
  { "DOTAMatchVote_NEGATIVE", "DOTAMATCH_VOTE__DOTAMatchVote_NEGATIVE", 2 },
};
static const ProtobufCIntRange dotamatch_vote__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex dotamatch_vote__enum_values_by_name[3] =
{
  { "DOTAMatchVote_INVALID", 0 },
  { "DOTAMatchVote_NEGATIVE", 2 },
  { "DOTAMatchVote_POSITIVE", 1 },
};
const ProtobufCEnumDescriptor dotamatch_vote__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTAMatchVote",
  "DOTAMatchVote",
  "DOTAMatchVote",
  "",
  3,
  dotamatch_vote__enum_values_by_number,
  3,
  dotamatch_vote__enum_values_by_name,
  1,
  dotamatch_vote__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dota__lobby_member_xpbonus__enum_values_by_number[6] =
{
  { "DOTA_LobbyMemberXPBonus_DEFAULT", "DOTA__LOBBY_MEMBER_XPBONUS__DOTA_LobbyMemberXPBonus_DEFAULT", 0 },
  { "DOTA_LobbyMemberXPBonus_BATTLE_BOOSTER", "DOTA__LOBBY_MEMBER_XPBONUS__DOTA_LobbyMemberXPBonus_BATTLE_BOOSTER", 1 },
  { "DOTA_LobbyMemberXPBonus_SHARE_BONUS", "DOTA__LOBBY_MEMBER_XPBONUS__DOTA_LobbyMemberXPBonus_SHARE_BONUS", 2 },
  { "DOTA_LobbyMemberXPBonus_PARTY", "DOTA__LOBBY_MEMBER_XPBONUS__DOTA_LobbyMemberXPBonus_PARTY", 3 },
  { "DOTA_LobbyMemberXPBonus_RECRUITMENT", "DOTA__LOBBY_MEMBER_XPBONUS__DOTA_LobbyMemberXPBonus_RECRUITMENT", 4 },
  { "DOTA_LobbyMemberXPBonus_PCBANG", "DOTA__LOBBY_MEMBER_XPBONUS__DOTA_LobbyMemberXPBonus_PCBANG", 5 },
};
static const ProtobufCIntRange dota__lobby_member_xpbonus__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex dota__lobby_member_xpbonus__enum_values_by_name[6] =
{
  { "DOTA_LobbyMemberXPBonus_BATTLE_BOOSTER", 1 },
  { "DOTA_LobbyMemberXPBonus_DEFAULT", 0 },
  { "DOTA_LobbyMemberXPBonus_PARTY", 3 },
  { "DOTA_LobbyMemberXPBonus_PCBANG", 5 },
  { "DOTA_LobbyMemberXPBonus_RECRUITMENT", 4 },
  { "DOTA_LobbyMemberXPBonus_SHARE_BONUS", 2 },
};
const ProtobufCEnumDescriptor dota__lobby_member_xpbonus__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTA_LobbyMemberXPBonus",
  "DOTA_LobbyMemberXPBonus",
  "DOTALobbyMemberXPBonus",
  "",
  6,
  dota__lobby_member_xpbonus__enum_values_by_number,
  6,
  dota__lobby_member_xpbonus__enum_values_by_name,
  1,
  dota__lobby_member_xpbonus__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dotalobby_visibility__enum_values_by_number[3] =
{
  { "DOTALobbyVisibility_Public", "DOTALOBBY_VISIBILITY__DOTALobbyVisibility_Public", 0 },
  { "DOTALobbyVisibility_Friends", "DOTALOBBY_VISIBILITY__DOTALobbyVisibility_Friends", 1 },
  { "DOTALobbyVisibility_Unlisted", "DOTALOBBY_VISIBILITY__DOTALobbyVisibility_Unlisted", 2 },
};
static const ProtobufCIntRange dotalobby_visibility__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex dotalobby_visibility__enum_values_by_name[3] =
{
  { "DOTALobbyVisibility_Friends", 1 },
  { "DOTALobbyVisibility_Public", 0 },
  { "DOTALobbyVisibility_Unlisted", 2 },
};
const ProtobufCEnumDescriptor dotalobby_visibility__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTALobbyVisibility",
  "DOTALobbyVisibility",
  "DOTALobbyVisibility",
  "",
  3,
  dotalobby_visibility__enum_values_by_number,
  3,
  dotalobby_visibility__enum_values_by_name,
  1,
  dotalobby_visibility__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue edotaplayer_mmrtype__enum_values_by_number[8] =
{
  { "k_EDOTAPlayerMMRType_Invalid", "EDOTAPLAYER_MMRTYPE__k_EDOTAPlayerMMRType_Invalid", 0 },
  { "k_EDOTAPlayerMMRType_GeneralHidden", "EDOTAPLAYER_MMRTYPE__k_EDOTAPlayerMMRType_GeneralHidden", 1 },
  { "k_EDOTAPlayerMMRType_SoloHidden", "EDOTAPLAYER_MMRTYPE__k_EDOTAPlayerMMRType_SoloHidden", 2 },
  { "k_EDOTAPlayerMMRType_GeneralCompetitive", "EDOTAPLAYER_MMRTYPE__k_EDOTAPlayerMMRType_GeneralCompetitive", 3 },
  { "k_EDOTAPlayerMMRType_SoloCompetitive", "EDOTAPLAYER_MMRTYPE__k_EDOTAPlayerMMRType_SoloCompetitive", 4 },
  { "k_EDOTAPlayerMMRType_1v1Competitive", "EDOTAPLAYER_MMRTYPE__k_EDOTAPlayerMMRType_1v1Competitive", 5 },
  { "k_EDOTAPlayerMMRType_GeneralSeasonalRanked", "EDOTAPLAYER_MMRTYPE__k_EDOTAPlayerMMRType_GeneralSeasonalRanked", 6 },
  { "k_EDOTAPlayerMMRType_SoloSeasonalRanked", "EDOTAPLAYER_MMRTYPE__k_EDOTAPlayerMMRType_SoloSeasonalRanked", 7 },
};
static const ProtobufCIntRange edotaplayer_mmrtype__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex edotaplayer_mmrtype__enum_values_by_name[8] =
{
  { "k_EDOTAPlayerMMRType_1v1Competitive", 5 },
  { "k_EDOTAPlayerMMRType_GeneralCompetitive", 3 },
  { "k_EDOTAPlayerMMRType_GeneralHidden", 1 },
  { "k_EDOTAPlayerMMRType_GeneralSeasonalRanked", 6 },
  { "k_EDOTAPlayerMMRType_Invalid", 0 },
  { "k_EDOTAPlayerMMRType_SoloCompetitive", 4 },
  { "k_EDOTAPlayerMMRType_SoloHidden", 2 },
  { "k_EDOTAPlayerMMRType_SoloSeasonalRanked", 7 },
};
const ProtobufCEnumDescriptor edotaplayer_mmrtype__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EDOTAPlayerMMRType",
  "EDOTAPlayerMMRType",
  "EDOTAPlayerMMRType",
  "",
  8,
  edotaplayer_mmrtype__enum_values_by_number,
  8,
  edotaplayer_mmrtype__enum_values_by_name,
  1,
  edotaplayer_mmrtype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue match_type__enum_values_by_number[9] =
{
  { "MATCH_TYPE_CASUAL", "MATCH_TYPE__MATCH_TYPE_CASUAL", 0 },
  { "MATCH_TYPE_COOP_BOTS", "MATCH_TYPE__MATCH_TYPE_COOP_BOTS", 1 },
  { "MATCH_TYPE_TEAM_RANKED", "MATCH_TYPE__MATCH_TYPE_TEAM_RANKED", 2 },
  { "MATCH_TYPE_LEGACY_SOLO_QUEUE", "MATCH_TYPE__MATCH_TYPE_LEGACY_SOLO_QUEUE", 3 },
  { "MATCH_TYPE_COMPETITIVE", "MATCH_TYPE__MATCH_TYPE_COMPETITIVE", 4 },
  { "MATCH_TYPE_WEEKEND_TOURNEY", "MATCH_TYPE__MATCH_TYPE_WEEKEND_TOURNEY", 5 },
  { "MATCH_TYPE_CASUAL_1V1", "MATCH_TYPE__MATCH_TYPE_CASUAL_1V1", 6 },
  { "MATCH_TYPE_EVENT", "MATCH_TYPE__MATCH_TYPE_EVENT", 7 },
  { "MATCH_TYPE_SEASONAL_RANKED", "MATCH_TYPE__MATCH_TYPE_SEASONAL_RANKED", 8 },
};
static const ProtobufCIntRange match_type__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex match_type__enum_values_by_name[9] =
{
  { "MATCH_TYPE_CASUAL", 0 },
  { "MATCH_TYPE_CASUAL_1V1", 6 },
  { "MATCH_TYPE_COMPETITIVE", 4 },
  { "MATCH_TYPE_COOP_BOTS", 1 },
  { "MATCH_TYPE_EVENT", 7 },
  { "MATCH_TYPE_LEGACY_SOLO_QUEUE", 3 },
  { "MATCH_TYPE_SEASONAL_RANKED", 8 },
  { "MATCH_TYPE_TEAM_RANKED", 2 },
  { "MATCH_TYPE_WEEKEND_TOURNEY", 5 },
};
const ProtobufCEnumDescriptor match_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MatchType",
  "MatchType",
  "MatchType",
  "",
  9,
  match_type__enum_values_by_number,
  9,
  match_type__enum_values_by_name,
  1,
  match_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dotabot_difficulty__enum_values_by_number[9] =
{
  { "BOT_DIFFICULTY_PASSIVE", "DOTABOT_DIFFICULTY__BOT_DIFFICULTY_PASSIVE", 0 },
  { "BOT_DIFFICULTY_EASY", "DOTABOT_DIFFICULTY__BOT_DIFFICULTY_EASY", 1 },
  { "BOT_DIFFICULTY_MEDIUM", "DOTABOT_DIFFICULTY__BOT_DIFFICULTY_MEDIUM", 2 },
  { "BOT_DIFFICULTY_HARD", "DOTABOT_DIFFICULTY__BOT_DIFFICULTY_HARD", 3 },
  { "BOT_DIFFICULTY_UNFAIR", "DOTABOT_DIFFICULTY__BOT_DIFFICULTY_UNFAIR", 4 },
  { "BOT_DIFFICULTY_INVALID", "DOTABOT_DIFFICULTY__BOT_DIFFICULTY_INVALID", 5 },
  { "BOT_DIFFICULTY_EXTRA1", "DOTABOT_DIFFICULTY__BOT_DIFFICULTY_EXTRA1", 6 },
  { "BOT_DIFFICULTY_EXTRA2", "DOTABOT_DIFFICULTY__BOT_DIFFICULTY_EXTRA2", 7 },
  { "BOT_DIFFICULTY_EXTRA3", "DOTABOT_DIFFICULTY__BOT_DIFFICULTY_EXTRA3", 8 },
};
static const ProtobufCIntRange dotabot_difficulty__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex dotabot_difficulty__enum_values_by_name[9] =
{
  { "BOT_DIFFICULTY_EASY", 1 },
  { "BOT_DIFFICULTY_EXTRA1", 6 },
  { "BOT_DIFFICULTY_EXTRA2", 7 },
  { "BOT_DIFFICULTY_EXTRA3", 8 },
  { "BOT_DIFFICULTY_HARD", 3 },
  { "BOT_DIFFICULTY_INVALID", 5 },
  { "BOT_DIFFICULTY_MEDIUM", 2 },
  { "BOT_DIFFICULTY_PASSIVE", 0 },
  { "BOT_DIFFICULTY_UNFAIR", 4 },
};
const ProtobufCEnumDescriptor dotabot_difficulty__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DOTABotDifficulty",
  "DOTABotDifficulty",
  "DOTABotDifficulty",
  "",
  9,
  dotabot_difficulty__enum_values_by_number,
  9,
  dotabot_difficulty__enum_values_by_name,
  1,
  dotabot_difficulty__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue match_languages__enum_values_by_number[8] =
{
  { "MATCH_LANGUAGE_INVALID", "MATCH_LANGUAGES__MATCH_LANGUAGE_INVALID", 0 },
  { "MATCH_LANGUAGE_ENGLISH", "MATCH_LANGUAGES__MATCH_LANGUAGE_ENGLISH", 1 },
  { "MATCH_LANGUAGE_RUSSIAN", "MATCH_LANGUAGES__MATCH_LANGUAGE_RUSSIAN", 2 },
  { "MATCH_LANGUAGE_CHINESE", "MATCH_LANGUAGES__MATCH_LANGUAGE_CHINESE", 3 },
  { "MATCH_LANGUAGE_KOREAN", "MATCH_LANGUAGES__MATCH_LANGUAGE_KOREAN", 4 },
  { "MATCH_LANGUAGE_SPANISH", "MATCH_LANGUAGES__MATCH_LANGUAGE_SPANISH", 5 },
  { "MATCH_LANGUAGE_PORTUGUESE", "MATCH_LANGUAGES__MATCH_LANGUAGE_PORTUGUESE", 6 },
  { "MATCH_LANGUAGE_ENGLISH2", "MATCH_LANGUAGES__MATCH_LANGUAGE_ENGLISH2", 7 },
};
static const ProtobufCIntRange match_languages__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex match_languages__enum_values_by_name[8] =
{
  { "MATCH_LANGUAGE_CHINESE", 3 },
  { "MATCH_LANGUAGE_ENGLISH", 1 },
  { "MATCH_LANGUAGE_ENGLISH2", 7 },
  { "MATCH_LANGUAGE_INVALID", 0 },
  { "MATCH_LANGUAGE_KOREAN", 4 },
  { "MATCH_LANGUAGE_PORTUGUESE", 6 },
  { "MATCH_LANGUAGE_RUSSIAN", 2 },
  { "MATCH_LANGUAGE_SPANISH", 5 },
};
const ProtobufCEnumDescriptor match_languages__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MatchLanguages",
  "MatchLanguages",
  "MatchLanguages",
  "",
  8,
  match_languages__enum_values_by_number,
  8,
  match_languages__enum_values_by_name,
  1,
  match_languages__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue etourney_queue_deadline_state__enum_values_by_number[7] =
{
  { "k_ETourneyQueueDeadlineState_NA", "ETOURNEY_QUEUE_DEADLINE_STATE__k_ETourneyQueueDeadlineState_NA", -1 },
  { "k_ETourneyQueueDeadlineState_Normal", "ETOURNEY_QUEUE_DEADLINE_STATE__k_ETourneyQueueDeadlineState_Normal", 0 },
  { "k_ETourneyQueueDeadlineState_Missed", "ETOURNEY_QUEUE_DEADLINE_STATE__k_ETourneyQueueDeadlineState_Missed", 1 },
  { "k_ETourneyQueueDeadlineState_ExpiredOK", "ETOURNEY_QUEUE_DEADLINE_STATE__k_ETourneyQueueDeadlineState_ExpiredOK", 2 },
  { "k_ETourneyQueueDeadlineState_SeekingBye", "ETOURNEY_QUEUE_DEADLINE_STATE__k_ETourneyQueueDeadlineState_SeekingBye", 3 },
  { "k_ETourneyQueueDeadlineState_EligibleForRefund", "ETOURNEY_QUEUE_DEADLINE_STATE__k_ETourneyQueueDeadlineState_EligibleForRefund", 4 },
  { "k_ETourneyQueueDeadlineState_ExpiringSoon", "ETOURNEY_QUEUE_DEADLINE_STATE__k_ETourneyQueueDeadlineState_ExpiringSoon", 101 },
};
static const ProtobufCIntRange etourney_queue_deadline_state__value_ranges[] = {
{-1, 0},{101, 6},{0, 7}
};
static const ProtobufCEnumValueIndex etourney_queue_deadline_state__enum_values_by_name[7] =
{
  { "k_ETourneyQueueDeadlineState_EligibleForRefund", 5 },
  { "k_ETourneyQueueDeadlineState_ExpiredOK", 3 },
  { "k_ETourneyQueueDeadlineState_ExpiringSoon", 6 },
  { "k_ETourneyQueueDeadlineState_Missed", 2 },
  { "k_ETourneyQueueDeadlineState_NA", 0 },
  { "k_ETourneyQueueDeadlineState_Normal", 1 },
  { "k_ETourneyQueueDeadlineState_SeekingBye", 4 },
};
const ProtobufCEnumDescriptor etourney_queue_deadline_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ETourneyQueueDeadlineState",
  "ETourneyQueueDeadlineState",
  "ETourneyQueueDeadlineState",
  "",
  7,
  etourney_queue_deadline_state__enum_values_by_number,
  7,
  etourney_queue_deadline_state__enum_values_by_name,
  2,
  etourney_queue_deadline_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ematch_outcome__enum_values_by_number[7] =
{
  { "k_EMatchOutcome_Unknown", "EMATCH_OUTCOME__k_EMatchOutcome_Unknown", 0 },
  { "k_EMatchOutcome_RadVictory", "EMATCH_OUTCOME__k_EMatchOutcome_RadVictory", 2 },
  { "k_EMatchOutcome_DireVictory", "EMATCH_OUTCOME__k_EMatchOutcome_DireVictory", 3 },
  { "k_EMatchOutcome_NotScored_PoorNetworkConditions", "EMATCH_OUTCOME__k_EMatchOutcome_NotScored_PoorNetworkConditions", 64 },
  { "k_EMatchOutcome_NotScored_Leaver", "EMATCH_OUTCOME__k_EMatchOutcome_NotScored_Leaver", 65 },
  { "k_EMatchOutcome_NotScored_ServerCrash", "EMATCH_OUTCOME__k_EMatchOutcome_NotScored_ServerCrash", 66 },
  { "k_EMatchOutcome_NotScored_NeverStarted", "EMATCH_OUTCOME__k_EMatchOutcome_NotScored_NeverStarted", 67 },
};
static const ProtobufCIntRange ematch_outcome__value_ranges[] = {
{0, 0},{2, 1},{64, 3},{0, 7}
};
static const ProtobufCEnumValueIndex ematch_outcome__enum_values_by_name[7] =
{
  { "k_EMatchOutcome_DireVictory", 2 },
  { "k_EMatchOutcome_NotScored_Leaver", 4 },
  { "k_EMatchOutcome_NotScored_NeverStarted", 6 },
  { "k_EMatchOutcome_NotScored_PoorNetworkConditions", 3 },
  { "k_EMatchOutcome_NotScored_ServerCrash", 5 },
  { "k_EMatchOutcome_RadVictory", 1 },
  { "k_EMatchOutcome_Unknown", 0 },
};
const ProtobufCEnumDescriptor ematch_outcome__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EMatchOutcome",
  "EMatchOutcome",
  "EMatchOutcome",
  "",
  7,
  ematch_outcome__enum_values_by_number,
  7,
  ematch_outcome__enum_values_by_name,
  3,
  ematch_outcome__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
