/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dota_client_enums.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dota_client_enums.pb-c.h"
static const ProtobufCEnumValue etournament_template__enum_values_by_number[2] =
{
  { "k_ETournamentTemplate_None", "ETOURNAMENT_TEMPLATE__k_ETournamentTemplate_None", 0 },
  { "k_ETournamentTemplate_AutomatedWin3", "ETOURNAMENT_TEMPLATE__k_ETournamentTemplate_AutomatedWin3", 1 },
};
static const ProtobufCIntRange etournament_template__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex etournament_template__enum_values_by_name[2] =
{
  { "k_ETournamentTemplate_AutomatedWin3", 1 },
  { "k_ETournamentTemplate_None", 0 },
};
const ProtobufCEnumDescriptor etournament_template__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ETournamentTemplate",
  "ETournamentTemplate",
  "ETournamentTemplate",
  "",
  2,
  etournament_template__enum_values_by_number,
  2,
  etournament_template__enum_values_by_name,
  1,
  etournament_template__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue etournament_game_state__enum_values_by_number[10] =
{
  { "k_ETournamentGameState_Unknown", "ETOURNAMENT_GAME_STATE__k_ETournamentGameState_Unknown", 0 },
  { "k_ETournamentGameState_Canceled", "ETOURNAMENT_GAME_STATE__k_ETournamentGameState_Canceled", 1 },
  { "k_ETournamentGameState_Scheduled", "ETOURNAMENT_GAME_STATE__k_ETournamentGameState_Scheduled", 2 },
  { "k_ETournamentGameState_Active", "ETOURNAMENT_GAME_STATE__k_ETournamentGameState_Active", 3 },
  { "k_ETournamentGameState_RadVictory", "ETOURNAMENT_GAME_STATE__k_ETournamentGameState_RadVictory", 20 },
  { "k_ETournamentGameState_DireVictory", "ETOURNAMENT_GAME_STATE__k_ETournamentGameState_DireVictory", 21 },
  { "k_ETournamentGameState_RadVictoryByForfeit", "ETOURNAMENT_GAME_STATE__k_ETournamentGameState_RadVictoryByForfeit", 22 },
  { "k_ETournamentGameState_DireVictoryByForfeit", "ETOURNAMENT_GAME_STATE__k_ETournamentGameState_DireVictoryByForfeit", 23 },
  { "k_ETournamentGameState_ServerFailure", "ETOURNAMENT_GAME_STATE__k_ETournamentGameState_ServerFailure", 40 },
  { "k_ETournamentGameState_NotNeeded", "ETOURNAMENT_GAME_STATE__k_ETournamentGameState_NotNeeded", 41 },
};
static const ProtobufCIntRange etournament_game_state__value_ranges[] = {
{0, 0},{20, 4},{40, 8},{0, 10}
};
static const ProtobufCEnumValueIndex etournament_game_state__enum_values_by_name[10] =
{
  { "k_ETournamentGameState_Active", 3 },
  { "k_ETournamentGameState_Canceled", 1 },
  { "k_ETournamentGameState_DireVictory", 5 },
  { "k_ETournamentGameState_DireVictoryByForfeit", 7 },
  { "k_ETournamentGameState_NotNeeded", 9 },
  { "k_ETournamentGameState_RadVictory", 4 },
  { "k_ETournamentGameState_RadVictoryByForfeit", 6 },
  { "k_ETournamentGameState_Scheduled", 2 },
  { "k_ETournamentGameState_ServerFailure", 8 },
  { "k_ETournamentGameState_Unknown", 0 },
};
const ProtobufCEnumDescriptor etournament_game_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ETournamentGameState",
  "ETournamentGameState",
  "ETournamentGameState",
  "",
  10,
  etournament_game_state__enum_values_by_number,
  10,
  etournament_game_state__enum_values_by_name,
  3,
  etournament_game_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue etournament_team_state__enum_values_by_number[21] =
{
  { "k_ETournamentTeamState_Unknown", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Unknown", 0 },
  { "k_ETournamentTeamState_Node1", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Node1", 1 },
  { "k_ETournamentTeamState_NodeMax", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_NodeMax", 1024 },
  { "k_ETournamentTeamState_Eliminated", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Eliminated", 14003 },
  { "k_ETournamentTeamState_Forfeited", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Forfeited", 14004 },
  { "k_ETournamentTeamState_Finished1st", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished1st", 15001 },
  { "k_ETournamentTeamState_Finished2nd", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished2nd", 15002 },
  { "k_ETournamentTeamState_Finished3rd", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished3rd", 15003 },
  { "k_ETournamentTeamState_Finished4th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished4th", 15004 },
  { "k_ETournamentTeamState_Finished5th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished5th", 15005 },
  { "k_ETournamentTeamState_Finished6th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished6th", 15006 },
  { "k_ETournamentTeamState_Finished7th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished7th", 15007 },
  { "k_ETournamentTeamState_Finished8th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished8th", 15008 },
  { "k_ETournamentTeamState_Finished9th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished9th", 15009 },
  { "k_ETournamentTeamState_Finished10th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished10th", 15010 },
  { "k_ETournamentTeamState_Finished11th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished11th", 15011 },
  { "k_ETournamentTeamState_Finished12th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished12th", 15012 },
  { "k_ETournamentTeamState_Finished13th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished13th", 15013 },
  { "k_ETournamentTeamState_Finished14th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished14th", 15014 },
  { "k_ETournamentTeamState_Finished15th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished15th", 15015 },
  { "k_ETournamentTeamState_Finished16th", "ETOURNAMENT_TEAM_STATE__k_ETournamentTeamState_Finished16th", 15016 },
};
static const ProtobufCIntRange etournament_team_state__value_ranges[] = {
{0, 0},{1024, 2},{14003, 3},{15001, 5},{0, 21}
};
static const ProtobufCEnumValueIndex etournament_team_state__enum_values_by_name[21] =
{
  { "k_ETournamentTeamState_Eliminated", 3 },
  { "k_ETournamentTeamState_Finished10th", 14 },
  { "k_ETournamentTeamState_Finished11th", 15 },
  { "k_ETournamentTeamState_Finished12th", 16 },
  { "k_ETournamentTeamState_Finished13th", 17 },
  { "k_ETournamentTeamState_Finished14th", 18 },
  { "k_ETournamentTeamState_Finished15th", 19 },
  { "k_ETournamentTeamState_Finished16th", 20 },
  { "k_ETournamentTeamState_Finished1st", 5 },
  { "k_ETournamentTeamState_Finished2nd", 6 },
  { "k_ETournamentTeamState_Finished3rd", 7 },
  { "k_ETournamentTeamState_Finished4th", 8 },
  { "k_ETournamentTeamState_Finished5th", 9 },
  { "k_ETournamentTeamState_Finished6th", 10 },
  { "k_ETournamentTeamState_Finished7th", 11 },
  { "k_ETournamentTeamState_Finished8th", 12 },
  { "k_ETournamentTeamState_Finished9th", 13 },
  { "k_ETournamentTeamState_Forfeited", 4 },
  { "k_ETournamentTeamState_Node1", 1 },
  { "k_ETournamentTeamState_NodeMax", 2 },
  { "k_ETournamentTeamState_Unknown", 0 },
};
const ProtobufCEnumDescriptor etournament_team_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ETournamentTeamState",
  "ETournamentTeamState",
  "ETournamentTeamState",
  "",
  21,
  etournament_team_state__enum_values_by_number,
  21,
  etournament_team_state__enum_values_by_name,
  4,
  etournament_team_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue etournament_state__enum_values_by_number[10] =
{
  { "k_ETournamentState_Unknown", "ETOURNAMENT_STATE__k_ETournamentState_Unknown", 0 },
  { "k_ETournamentState_CanceledByAdmin", "ETOURNAMENT_STATE__k_ETournamentState_CanceledByAdmin", 1 },
  { "k_ETournamentState_Completed", "ETOURNAMENT_STATE__k_ETournamentState_Completed", 2 },
  { "k_ETournamentState_Merged", "ETOURNAMENT_STATE__k_ETournamentState_Merged", 3 },
  { "k_ETournamentState_ServerFailure", "ETOURNAMENT_STATE__k_ETournamentState_ServerFailure", 4 },
  { "k_ETournamentState_TeamAbandoned", "ETOURNAMENT_STATE__k_ETournamentState_TeamAbandoned", 5 },
  { "k_ETournamentState_TeamTimeoutForfeit", "ETOURNAMENT_STATE__k_ETournamentState_TeamTimeoutForfeit", 6 },
  { "k_ETournamentState_TeamTimeoutRefund", "ETOURNAMENT_STATE__k_ETournamentState_TeamTimeoutRefund", 7 },
  { "k_ETournamentState_InProgress", "ETOURNAMENT_STATE__k_ETournamentState_InProgress", 100 },
  { "k_ETournamentState_WaitingToMerge", "ETOURNAMENT_STATE__k_ETournamentState_WaitingToMerge", 101 },
};
static const ProtobufCIntRange etournament_state__value_ranges[] = {
{0, 0},{100, 8},{0, 10}
};
static const ProtobufCEnumValueIndex etournament_state__enum_values_by_name[10] =
{
  { "k_ETournamentState_CanceledByAdmin", 1 },
  { "k_ETournamentState_Completed", 2 },
  { "k_ETournamentState_InProgress", 8 },
  { "k_ETournamentState_Merged", 3 },
  { "k_ETournamentState_ServerFailure", 4 },
  { "k_ETournamentState_TeamAbandoned", 5 },
  { "k_ETournamentState_TeamTimeoutForfeit", 6 },
  { "k_ETournamentState_TeamTimeoutRefund", 7 },
  { "k_ETournamentState_Unknown", 0 },
  { "k_ETournamentState_WaitingToMerge", 9 },
};
const ProtobufCEnumDescriptor etournament_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ETournamentState",
  "ETournamentState",
  "ETournamentState",
  "",
  10,
  etournament_state__enum_values_by_number,
  10,
  etournament_state__enum_values_by_name,
  2,
  etournament_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue etournament_node_state__enum_values_by_number[14] =
{
  { "k_ETournamentNodeState_Unknown", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_Unknown", 0 },
  { "k_ETournamentNodeState_Canceled", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_Canceled", 1 },
  { "k_ETournamentNodeState_TeamsNotYetAssigned", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_TeamsNotYetAssigned", 2 },
  { "k_ETournamentNodeState_InBetweenGames", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_InBetweenGames", 3 },
  { "k_ETournamentNodeState_GameInProgress", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_GameInProgress", 4 },
  { "k_ETournamentNodeState_A_Won", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_A_Won", 5 },
  { "k_ETournamentNodeState_B_Won", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_B_Won", 6 },
  { "k_ETournamentNodeState_A_WonByForfeit", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_A_WonByForfeit", 7 },
  { "k_ETournamentNodeState_B_WonByForfeit", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_B_WonByForfeit", 8 },
  { "k_ETournamentNodeState_A_Bye", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_A_Bye", 9 },
  { "k_ETournamentNodeState_A_Abandoned", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_A_Abandoned", 10 },
  { "k_ETournamentNodeState_ServerFailure", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_ServerFailure", 11 },
  { "k_ETournamentNodeState_A_TimeoutForfeit", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_A_TimeoutForfeit", 12 },
  { "k_ETournamentNodeState_A_TimeoutRefund", "ETOURNAMENT_NODE_STATE__k_ETournamentNodeState_A_TimeoutRefund", 13 },
};
static const ProtobufCIntRange etournament_node_state__value_ranges[] = {
{0, 0},{0, 14}
};
static const ProtobufCEnumValueIndex etournament_node_state__enum_values_by_name[14] =
{
  { "k_ETournamentNodeState_A_Abandoned", 10 },
  { "k_ETournamentNodeState_A_Bye", 9 },
  { "k_ETournamentNodeState_A_TimeoutForfeit", 12 },
  { "k_ETournamentNodeState_A_TimeoutRefund", 13 },
  { "k_ETournamentNodeState_A_Won", 5 },
  { "k_ETournamentNodeState_A_WonByForfeit", 7 },
  { "k_ETournamentNodeState_B_Won", 6 },
  { "k_ETournamentNodeState_B_WonByForfeit", 8 },
  { "k_ETournamentNodeState_Canceled", 1 },
  { "k_ETournamentNodeState_GameInProgress", 4 },
  { "k_ETournamentNodeState_InBetweenGames", 3 },
  { "k_ETournamentNodeState_ServerFailure", 11 },
  { "k_ETournamentNodeState_TeamsNotYetAssigned", 2 },
  { "k_ETournamentNodeState_Unknown", 0 },
};
const ProtobufCEnumDescriptor etournament_node_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ETournamentNodeState",
  "ETournamentNodeState",
  "ETournamentNodeState",
  "",
  14,
  etournament_node_state__enum_values_by_number,
  14,
  etournament_node_state__enum_values_by_name,
  1,
  etournament_node_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue edotagroup_merge_result__enum_values_by_number[10] =
{
  { "k_EDOTAGroupMergeResult_OK", "EDOTAGROUP_MERGE_RESULT__k_EDOTAGroupMergeResult_OK", 0 },
  { "k_EDOTAGroupMergeResult_FAILED_GENERIC", "EDOTAGROUP_MERGE_RESULT__k_EDOTAGroupMergeResult_FAILED_GENERIC", 1 },
  { "k_EDOTAGroupMergeResult_NOT_LEADER", "EDOTAGROUP_MERGE_RESULT__k_EDOTAGroupMergeResult_NOT_LEADER", 2 },
  { "k_EDOTAGroupMergeResult_TOO_MANY_PLAYERS", "EDOTAGROUP_MERGE_RESULT__k_EDOTAGroupMergeResult_TOO_MANY_PLAYERS", 3 },
  { "k_EDOTAGroupMergeResult_TOO_MANY_COACHES", "EDOTAGROUP_MERGE_RESULT__k_EDOTAGroupMergeResult_TOO_MANY_COACHES", 4 },
  { "k_EDOTAGroupMergeResult_ENGINE_MISMATCH", "EDOTAGROUP_MERGE_RESULT__k_EDOTAGroupMergeResult_ENGINE_MISMATCH", 5 },
  { "k_EDOTAGroupMergeResult_NO_SUCH_GROUP", "EDOTAGROUP_MERGE_RESULT__k_EDOTAGroupMergeResult_NO_SUCH_GROUP", 6 },
  { "k_EDOTAGroupMergeResult_OTHER_GROUP_NOT_OPEN", "EDOTAGROUP_MERGE_RESULT__k_EDOTAGroupMergeResult_OTHER_GROUP_NOT_OPEN", 7 },
  { "k_EDOTAGroupMergeResult_ALREADY_INVITED", "EDOTAGROUP_MERGE_RESULT__k_EDOTAGroupMergeResult_ALREADY_INVITED", 8 },
  { "k_EDOTAGroupMergeResult_NOT_INVITED", "EDOTAGROUP_MERGE_RESULT__k_EDOTAGroupMergeResult_NOT_INVITED", 9 },
};
static const ProtobufCIntRange edotagroup_merge_result__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex edotagroup_merge_result__enum_values_by_name[10] =
{
  { "k_EDOTAGroupMergeResult_ALREADY_INVITED", 8 },
  { "k_EDOTAGroupMergeResult_ENGINE_MISMATCH", 5 },
  { "k_EDOTAGroupMergeResult_FAILED_GENERIC", 1 },
  { "k_EDOTAGroupMergeResult_NOT_INVITED", 9 },
  { "k_EDOTAGroupMergeResult_NOT_LEADER", 2 },
  { "k_EDOTAGroupMergeResult_NO_SUCH_GROUP", 6 },
  { "k_EDOTAGroupMergeResult_OK", 0 },
  { "k_EDOTAGroupMergeResult_OTHER_GROUP_NOT_OPEN", 7 },
  { "k_EDOTAGroupMergeResult_TOO_MANY_COACHES", 4 },
  { "k_EDOTAGroupMergeResult_TOO_MANY_PLAYERS", 3 },
};
const ProtobufCEnumDescriptor edotagroup_merge_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EDOTAGroupMergeResult",
  "EDOTAGroupMergeResult",
  "EDOTAGroupMergeResult",
  "",
  10,
  edotagroup_merge_result__enum_values_by_number,
  10,
  edotagroup_merge_result__enum_values_by_name,
  1,
  edotagroup_merge_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
