/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: econ_shared_enums.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "econ_shared_enums.pb-c.h"
void   cmsg_generic_result__init
                     (CMsgGenericResult         *message)
{
  static CMsgGenericResult init_value = CMSG_GENERIC_RESULT__INIT;
  *message = init_value;
}
size_t cmsg_generic_result__get_packed_size
                     (const CMsgGenericResult *message)
{
  assert(message->base.descriptor == &cmsg_generic_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_generic_result__pack
                     (const CMsgGenericResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_generic_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_generic_result__pack_to_buffer
                     (const CMsgGenericResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_generic_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgGenericResult *
       cmsg_generic_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgGenericResult *)
     protobuf_c_message_unpack (&cmsg_generic_result__descriptor,
                                allocator, len, data);
}
void   cmsg_generic_result__free_unpacked
                     (CMsgGenericResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmsg_generic_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const uint32_t cmsg_generic_result__eresult__default_value = 2u;
static const ProtobufCFieldDescriptor cmsg_generic_result__field_descriptors[2] =
{
  {
    "eresult",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgGenericResult, has_eresult),
    offsetof(CMsgGenericResult, eresult),
    NULL,
    &cmsg_generic_result__eresult__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "debug_message",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgGenericResult, debug_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_generic_result__field_indices_by_name[] = {
  1,   /* field[1] = debug_message */
  0,   /* field[0] = eresult */
};
static const ProtobufCIntRange cmsg_generic_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_generic_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgGenericResult",
  "CMsgGenericResult",
  "CMsgGenericResult",
  "",
  sizeof(CMsgGenericResult),
  2,
  cmsg_generic_result__field_descriptors,
  cmsg_generic_result__field_indices_by_name,
  1,  cmsg_generic_result__number_ranges,
  (ProtobufCMessageInit) cmsg_generic_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue egcecon_base_msg__enum_values_by_number[1] =
{
  { "k_EMsgGCGenericResult", "EGCECON_BASE_MSG__k_EMsgGCGenericResult", 2579 },
};
static const ProtobufCIntRange egcecon_base_msg__value_ranges[] = {
{2579, 0},{0, 1}
};
static const ProtobufCEnumValueIndex egcecon_base_msg__enum_values_by_name[1] =
{
  { "k_EMsgGCGenericResult", 0 },
};
const ProtobufCEnumDescriptor egcecon_base_msg__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EGCEconBaseMsg",
  "EGCEconBaseMsg",
  "EGCEconBaseMsg",
  "",
  1,
  egcecon_base_msg__enum_values_by_number,
  1,
  egcecon_base_msg__enum_values_by_name,
  1,
  egcecon_base_msg__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue egcmsg_response__enum_values_by_number[9] =
{
  { "k_EGCMsgResponseOK", "EGCMSG_RESPONSE__k_EGCMsgResponseOK", 0 },
  { "k_EGCMsgResponseDenied", "EGCMSG_RESPONSE__k_EGCMsgResponseDenied", 1 },
  { "k_EGCMsgResponseServerError", "EGCMSG_RESPONSE__k_EGCMsgResponseServerError", 2 },
  { "k_EGCMsgResponseTimeout", "EGCMSG_RESPONSE__k_EGCMsgResponseTimeout", 3 },
  { "k_EGCMsgResponseInvalid", "EGCMSG_RESPONSE__k_EGCMsgResponseInvalid", 4 },
  { "k_EGCMsgResponseNoMatch", "EGCMSG_RESPONSE__k_EGCMsgResponseNoMatch", 5 },
  { "k_EGCMsgResponseUnknownError", "EGCMSG_RESPONSE__k_EGCMsgResponseUnknownError", 6 },
  { "k_EGCMsgResponseNotLoggedOn", "EGCMSG_RESPONSE__k_EGCMsgResponseNotLoggedOn", 7 },
  { "k_EGCMsgFailedToCreate", "EGCMSG_RESPONSE__k_EGCMsgFailedToCreate", 8 },
};
static const ProtobufCIntRange egcmsg_response__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex egcmsg_response__enum_values_by_name[9] =
{
  { "k_EGCMsgFailedToCreate", 8 },
  { "k_EGCMsgResponseDenied", 1 },
  { "k_EGCMsgResponseInvalid", 4 },
  { "k_EGCMsgResponseNoMatch", 5 },
  { "k_EGCMsgResponseNotLoggedOn", 7 },
  { "k_EGCMsgResponseOK", 0 },
  { "k_EGCMsgResponseServerError", 2 },
  { "k_EGCMsgResponseTimeout", 3 },
  { "k_EGCMsgResponseUnknownError", 6 },
};
const ProtobufCEnumDescriptor egcmsg_response__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EGCMsgResponse",
  "EGCMsgResponse",
  "EGCMsgResponse",
  "",
  9,
  egcmsg_response__enum_values_by_number,
  9,
  egcmsg_response__enum_values_by_name,
  1,
  egcmsg_response__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue egcpartner_request_response__enum_values_by_number[4] =
{
  { "k_EPartnerRequestOK", "EGCPARTNER_REQUEST_RESPONSE__k_EPartnerRequestOK", 1 },
  { "k_EPartnerRequestBadAccount", "EGCPARTNER_REQUEST_RESPONSE__k_EPartnerRequestBadAccount", 2 },
  { "k_EPartnerRequestNotLinked", "EGCPARTNER_REQUEST_RESPONSE__k_EPartnerRequestNotLinked", 3 },
  { "k_EPartnerRequestUnsupportedPartnerType", "EGCPARTNER_REQUEST_RESPONSE__k_EPartnerRequestUnsupportedPartnerType", 4 },
};
static const ProtobufCIntRange egcpartner_request_response__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex egcpartner_request_response__enum_values_by_name[4] =
{
  { "k_EPartnerRequestBadAccount", 1 },
  { "k_EPartnerRequestNotLinked", 2 },
  { "k_EPartnerRequestOK", 0 },
  { "k_EPartnerRequestUnsupportedPartnerType", 3 },
};
const ProtobufCEnumDescriptor egcpartner_request_response__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EGCPartnerRequestResponse",
  "EGCPartnerRequestResponse",
  "EGCPartnerRequestResponse",
  "",
  4,
  egcpartner_request_response__enum_values_by_number,
  4,
  egcpartner_request_response__enum_values_by_name,
  1,
  egcpartner_request_response__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue egcmsg_use_item_response__enum_values_by_number[14] =
{
  { "k_EGCMsgUseItemResponse_ItemUsed", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_ItemUsed", 0 },
  { "k_EGCMsgUseItemResponse_GiftNoOtherPlayers", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_GiftNoOtherPlayers", 1 },
  { "k_EGCMsgUseItemResponse_ServerError", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_ServerError", 2 },
  { "k_EGCMsgUseItemResponse_MiniGameAlreadyStarted", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_MiniGameAlreadyStarted", 3 },
  { "k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted", 4 },
  { "k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted", 5 },
  { "k_EGCMsgUseItemResponse_NotInLowPriorityPool", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_NotInLowPriorityPool", 6 },
  { "k_EGCMsgUseItemResponse_NotHighEnoughLevel", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_NotHighEnoughLevel", 7 },
  { "k_EGCMsgUseItemResponse_EventNotActive", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_EventNotActive", 8 },
  { "k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted", 9 },
  { "k_EGCMsgUseItemResponse_MissingRequirement", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_MissingRequirement", 10 },
  { "k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew", 11 },
  { "k_EGCMsgUseItemResponse_EmoticonUnlock_Complete", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_EmoticonUnlock_Complete", 12 },
  { "k_EGCMsgUseItemResponse_ItemUsed_Compendium", "EGCMSG_USE_ITEM_RESPONSE__k_EGCMsgUseItemResponse_ItemUsed_Compendium", 13 },
};
static const ProtobufCIntRange egcmsg_use_item_response__value_ranges[] = {
{0, 0},{0, 14}
};
static const ProtobufCEnumValueIndex egcmsg_use_item_response__enum_values_by_name[14] =
{
  { "k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted", 5 },
  { "k_EGCMsgUseItemResponse_EmoticonUnlock_Complete", 12 },
  { "k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew", 11 },
  { "k_EGCMsgUseItemResponse_EventNotActive", 8 },
  { "k_EGCMsgUseItemResponse_GiftNoOtherPlayers", 1 },
  { "k_EGCMsgUseItemResponse_ItemUsed", 0 },
  { "k_EGCMsgUseItemResponse_ItemUsed_Compendium", 13 },
  { "k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted", 9 },
  { "k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted", 4 },
  { "k_EGCMsgUseItemResponse_MiniGameAlreadyStarted", 3 },
  { "k_EGCMsgUseItemResponse_MissingRequirement", 10 },
  { "k_EGCMsgUseItemResponse_NotHighEnoughLevel", 7 },
  { "k_EGCMsgUseItemResponse_NotInLowPriorityPool", 6 },
  { "k_EGCMsgUseItemResponse_ServerError", 2 },
};
const ProtobufCEnumDescriptor egcmsg_use_item_response__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EGCMsgUseItemResponse",
  "EGCMsgUseItemResponse",
  "EGCMsgUseItemResponse",
  "",
  14,
  egcmsg_use_item_response__enum_values_by_number,
  14,
  egcmsg_use_item_response__enum_values_by_name,
  1,
  egcmsg_use_item_response__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
