/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: networksystem_protomessages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "networksystem_protomessages.pb-c.h"
void   net_message_splitscreen_user_changed__init
                     (NetMessageSplitscreenUserChanged         *message)
{
  static NetMessageSplitscreenUserChanged init_value = NET_MESSAGE_SPLITSCREEN_USER_CHANGED__INIT;
  *message = init_value;
}
size_t net_message_splitscreen_user_changed__get_packed_size
                     (const NetMessageSplitscreenUserChanged *message)
{
  assert(message->base.descriptor == &net_message_splitscreen_user_changed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_message_splitscreen_user_changed__pack
                     (const NetMessageSplitscreenUserChanged *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &net_message_splitscreen_user_changed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_message_splitscreen_user_changed__pack_to_buffer
                     (const NetMessageSplitscreenUserChanged *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &net_message_splitscreen_user_changed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetMessageSplitscreenUserChanged *
       net_message_splitscreen_user_changed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetMessageSplitscreenUserChanged *)
     protobuf_c_message_unpack (&net_message_splitscreen_user_changed__descriptor,
                                allocator, len, data);
}
void   net_message_splitscreen_user_changed__free_unpacked
                     (NetMessageSplitscreenUserChanged *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &net_message_splitscreen_user_changed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   net_message_connection_closed__init
                     (NetMessageConnectionClosed         *message)
{
  static NetMessageConnectionClosed init_value = NET_MESSAGE_CONNECTION_CLOSED__INIT;
  *message = init_value;
}
size_t net_message_connection_closed__get_packed_size
                     (const NetMessageConnectionClosed *message)
{
  assert(message->base.descriptor == &net_message_connection_closed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_message_connection_closed__pack
                     (const NetMessageConnectionClosed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &net_message_connection_closed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_message_connection_closed__pack_to_buffer
                     (const NetMessageConnectionClosed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &net_message_connection_closed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetMessageConnectionClosed *
       net_message_connection_closed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetMessageConnectionClosed *)
     protobuf_c_message_unpack (&net_message_connection_closed__descriptor,
                                allocator, len, data);
}
void   net_message_connection_closed__free_unpacked
                     (NetMessageConnectionClosed *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &net_message_connection_closed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   net_message_connection_crashed__init
                     (NetMessageConnectionCrashed         *message)
{
  static NetMessageConnectionCrashed init_value = NET_MESSAGE_CONNECTION_CRASHED__INIT;
  *message = init_value;
}
size_t net_message_connection_crashed__get_packed_size
                     (const NetMessageConnectionCrashed *message)
{
  assert(message->base.descriptor == &net_message_connection_crashed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_message_connection_crashed__pack
                     (const NetMessageConnectionCrashed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &net_message_connection_crashed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_message_connection_crashed__pack_to_buffer
                     (const NetMessageConnectionCrashed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &net_message_connection_crashed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetMessageConnectionCrashed *
       net_message_connection_crashed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetMessageConnectionCrashed *)
     protobuf_c_message_unpack (&net_message_connection_crashed__descriptor,
                                allocator, len, data);
}
void   net_message_connection_crashed__free_unpacked
                     (NetMessageConnectionCrashed *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &net_message_connection_crashed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   net_message_packet_start__init
                     (NetMessagePacketStart         *message)
{
  static NetMessagePacketStart init_value = NET_MESSAGE_PACKET_START__INIT;
  *message = init_value;
}
size_t net_message_packet_start__get_packed_size
                     (const NetMessagePacketStart *message)
{
  assert(message->base.descriptor == &net_message_packet_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_message_packet_start__pack
                     (const NetMessagePacketStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &net_message_packet_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_message_packet_start__pack_to_buffer
                     (const NetMessagePacketStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &net_message_packet_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetMessagePacketStart *
       net_message_packet_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetMessagePacketStart *)
     protobuf_c_message_unpack (&net_message_packet_start__descriptor,
                                allocator, len, data);
}
void   net_message_packet_start__free_unpacked
                     (NetMessagePacketStart *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &net_message_packet_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   net_message_packet_end__init
                     (NetMessagePacketEnd         *message)
{
  static NetMessagePacketEnd init_value = NET_MESSAGE_PACKET_END__INIT;
  *message = init_value;
}
size_t net_message_packet_end__get_packed_size
                     (const NetMessagePacketEnd *message)
{
  assert(message->base.descriptor == &net_message_packet_end__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_message_packet_end__pack
                     (const NetMessagePacketEnd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &net_message_packet_end__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_message_packet_end__pack_to_buffer
                     (const NetMessagePacketEnd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &net_message_packet_end__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetMessagePacketEnd *
       net_message_packet_end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetMessagePacketEnd *)
     protobuf_c_message_unpack (&net_message_packet_end__descriptor,
                                allocator, len, data);
}
void   net_message_packet_end__free_unpacked
                     (NetMessagePacketEnd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &net_message_packet_end__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor net_message_splitscreen_user_changed__field_descriptors[1] =
{
  {
    "slot",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetMessageSplitscreenUserChanged, has_slot),
    offsetof(NetMessageSplitscreenUserChanged, slot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned net_message_splitscreen_user_changed__field_indices_by_name[] = {
  0,   /* field[0] = slot */
};
static const ProtobufCIntRange net_message_splitscreen_user_changed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor net_message_splitscreen_user_changed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetMessageSplitscreenUserChanged",
  "NetMessageSplitscreenUserChanged",
  "NetMessageSplitscreenUserChanged",
  "",
  sizeof(NetMessageSplitscreenUserChanged),
  1,
  net_message_splitscreen_user_changed__field_descriptors,
  net_message_splitscreen_user_changed__field_indices_by_name,
  1,  net_message_splitscreen_user_changed__number_ranges,
  (ProtobufCMessageInit) net_message_splitscreen_user_changed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor net_message_connection_closed__field_descriptors[1] =
{
  {
    "reason",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetMessageConnectionClosed, has_reason),
    offsetof(NetMessageConnectionClosed, reason),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned net_message_connection_closed__field_indices_by_name[] = {
  0,   /* field[0] = reason */
};
static const ProtobufCIntRange net_message_connection_closed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor net_message_connection_closed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetMessageConnectionClosed",
  "NetMessageConnectionClosed",
  "NetMessageConnectionClosed",
  "",
  sizeof(NetMessageConnectionClosed),
  1,
  net_message_connection_closed__field_descriptors,
  net_message_connection_closed__field_indices_by_name,
  1,  net_message_connection_closed__number_ranges,
  (ProtobufCMessageInit) net_message_connection_closed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor net_message_connection_crashed__field_descriptors[1] =
{
  {
    "reason",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetMessageConnectionCrashed, has_reason),
    offsetof(NetMessageConnectionCrashed, reason),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned net_message_connection_crashed__field_indices_by_name[] = {
  0,   /* field[0] = reason */
};
static const ProtobufCIntRange net_message_connection_crashed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor net_message_connection_crashed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetMessageConnectionCrashed",
  "NetMessageConnectionCrashed",
  "NetMessageConnectionCrashed",
  "",
  sizeof(NetMessageConnectionCrashed),
  1,
  net_message_connection_crashed__field_descriptors,
  net_message_connection_crashed__field_indices_by_name,
  1,  net_message_connection_crashed__number_ranges,
  (ProtobufCMessageInit) net_message_connection_crashed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor net_message_packet_start__field_descriptors[2] =
{
  {
    "incoming_sequence",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetMessagePacketStart, has_incoming_sequence),
    offsetof(NetMessagePacketStart, incoming_sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outgoing_acknowledged",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetMessagePacketStart, has_outgoing_acknowledged),
    offsetof(NetMessagePacketStart, outgoing_acknowledged),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned net_message_packet_start__field_indices_by_name[] = {
  0,   /* field[0] = incoming_sequence */
  1,   /* field[1] = outgoing_acknowledged */
};
static const ProtobufCIntRange net_message_packet_start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor net_message_packet_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetMessagePacketStart",
  "NetMessagePacketStart",
  "NetMessagePacketStart",
  "",
  sizeof(NetMessagePacketStart),
  2,
  net_message_packet_start__field_descriptors,
  net_message_packet_start__field_indices_by_name,
  1,  net_message_packet_start__number_ranges,
  (ProtobufCMessageInit) net_message_packet_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define net_message_packet_end__field_descriptors NULL
#define net_message_packet_end__field_indices_by_name NULL
#define net_message_packet_end__number_ranges NULL
const ProtobufCMessageDescriptor net_message_packet_end__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetMessagePacketEnd",
  "NetMessagePacketEnd",
  "NetMessagePacketEnd",
  "",
  sizeof(NetMessagePacketEnd),
  0,
  net_message_packet_end__field_descriptors,
  net_message_packet_end__field_indices_by_name,
  0,  net_message_packet_end__number_ranges,
  (ProtobufCMessageInit) net_message_packet_end__init,
  NULL,NULL,NULL    /* reserved[123] */
};
