/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steammessages_oauth.steamworkssdk.proto */

#ifndef PROTOBUF_C_steammessages_5foauth_2esteamworkssdk_2eproto__INCLUDED
#define PROTOBUF_C_steammessages_5foauth_2esteamworkssdk_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "steammessages_unified_base.steamworkssdk.pb-c.h"

typedef struct _COAuthTokenImplicitGrantNoPromptRequest COAuthTokenImplicitGrantNoPromptRequest;
typedef struct _COAuthTokenImplicitGrantNoPromptResponse COAuthTokenImplicitGrantNoPromptResponse;


/* --- enums --- */


/* --- messages --- */

struct  _COAuthTokenImplicitGrantNoPromptRequest
{
  ProtobufCMessage base;
  char *clientid;
};
#define COAUTH_TOKEN__IMPLICIT_GRANT_NO_PROMPT__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&coauth_token__implicit_grant_no_prompt__request__descriptor) \
    , NULL }


struct  _COAuthTokenImplicitGrantNoPromptResponse
{
  ProtobufCMessage base;
  char *access_token;
  char *redirect_uri;
};
#define COAUTH_TOKEN__IMPLICIT_GRANT_NO_PROMPT__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&coauth_token__implicit_grant_no_prompt__response__descriptor) \
    , NULL, NULL }


/* COAuthTokenImplicitGrantNoPromptRequest methods */
void   coauth_token__implicit_grant_no_prompt__request__init
                     (COAuthTokenImplicitGrantNoPromptRequest         *message);
size_t coauth_token__implicit_grant_no_prompt__request__get_packed_size
                     (const COAuthTokenImplicitGrantNoPromptRequest   *message);
size_t coauth_token__implicit_grant_no_prompt__request__pack
                     (const COAuthTokenImplicitGrantNoPromptRequest   *message,
                      uint8_t             *out);
size_t coauth_token__implicit_grant_no_prompt__request__pack_to_buffer
                     (const COAuthTokenImplicitGrantNoPromptRequest   *message,
                      ProtobufCBuffer     *buffer);
COAuthTokenImplicitGrantNoPromptRequest *
       coauth_token__implicit_grant_no_prompt__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   coauth_token__implicit_grant_no_prompt__request__free_unpacked
                     (COAuthTokenImplicitGrantNoPromptRequest *message,
                      ProtobufCAllocator *allocator);
/* COAuthTokenImplicitGrantNoPromptResponse methods */
void   coauth_token__implicit_grant_no_prompt__response__init
                     (COAuthTokenImplicitGrantNoPromptResponse         *message);
size_t coauth_token__implicit_grant_no_prompt__response__get_packed_size
                     (const COAuthTokenImplicitGrantNoPromptResponse   *message);
size_t coauth_token__implicit_grant_no_prompt__response__pack
                     (const COAuthTokenImplicitGrantNoPromptResponse   *message,
                      uint8_t             *out);
size_t coauth_token__implicit_grant_no_prompt__response__pack_to_buffer
                     (const COAuthTokenImplicitGrantNoPromptResponse   *message,
                      ProtobufCBuffer     *buffer);
COAuthTokenImplicitGrantNoPromptResponse *
       coauth_token__implicit_grant_no_prompt__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   coauth_token__implicit_grant_no_prompt__response__free_unpacked
                     (COAuthTokenImplicitGrantNoPromptResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*COAuthTokenImplicitGrantNoPromptRequest_Closure)
                 (const COAuthTokenImplicitGrantNoPromptRequest *message,
                  void *closure_data);
typedef void (*COAuthTokenImplicitGrantNoPromptResponse_Closure)
                 (const COAuthTokenImplicitGrantNoPromptResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct _OAuthToken_Service OAuthToken_Service;
struct _OAuthToken_Service
{
  ProtobufCService base;
  void (*implicit_grant_no_prompt)(OAuthToken_Service *service,
                                   const COAuthTokenImplicitGrantNoPromptRequest *input,
                                   COAuthTokenImplicitGrantNoPromptResponse_Closure closure,
                                   void *closure_data);
};
typedef void (*OAuthToken_ServiceDestroy)(OAuthToken_Service *);
void oauth_token__init (OAuthToken_Service *service,
                        OAuthToken_ServiceDestroy destroy);
#define OAUTH_TOKEN__BASE_INIT \
    { &oauth_token__descriptor, protobuf_c_service_invoke_internal, NULL }
#define OAUTH_TOKEN__INIT(function_prefix__) \
    { OAUTH_TOKEN__BASE_INIT,\
      function_prefix__ ## implicit_grant_no_prompt  }
void oauth_token__implicit_grant_no_prompt(ProtobufCService *service,
                                           const COAuthTokenImplicitGrantNoPromptRequest *input,
                                           COAuthTokenImplicitGrantNoPromptResponse_Closure closure,
                                           void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor coauth_token__implicit_grant_no_prompt__request__descriptor;
extern const ProtobufCMessageDescriptor coauth_token__implicit_grant_no_prompt__response__descriptor;
extern const ProtobufCServiceDescriptor oauth_token__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steammessages_5foauth_2esteamworkssdk_2eproto__INCLUDED */
